package obs_test

import (
	"context"
	"errors"
	"sync"
	"testing"
	"testing/synctest"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/SkylinePlatform/agentic-payments/backend/internal/core/generated"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/clock"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/obs"
)

var base = time.Date(2026, 8, 4, 12, 0, 0, 0, time.UTC)

// The sinks below are obs.MockSink, generated by mockery from obs.Sink into
// mocks_test.go — see backend/.mockery.yml. The emitter calls Send from its
// own goroutine, which is what makes a generated mock worth having here: the
// call count is kept under testify's mutex rather than one this file has to
// remember to take, and "was Send called again after it failed" is a question
// answered by AssertNumberOfCalls instead of by a counter of ours.
//
// Nothing else about a batch is captured by hand either. What a test needs to
// look at arrives on a channel, so every read of it is on the test goroutine.

// recording returns a sink that reports each batch on the returned channel and
// answers every call with err. A test waits on the channel instead of sleeping.
func recording(t *testing.T, err error) (*obs.MockSink, chan []obs.Event) {
	t.Helper()
	sent := make(chan []obs.Event, 64)
	sink := obs.NewMockSink(t)
	sink.EXPECT().Send(mock.Anything, mock.Anything).
		RunAndReturn(func(_ context.Context, batch []obs.Event) error {
			sent <- batch
			return err
		}).Maybe()
	return sink, sent
}

// delivered drains what the sink was sent. Close flushes before it returns, so
// by the time a test calls this every batch is already on the channel.
func delivered(sent chan []obs.Event) []obs.Event {
	var got []obs.Event
	for {
		select {
		case batch := <-sent:
			got = append(got, batch...)
		default:
			return got
		}
	}
}

// blocking returns a sink that parks inside Send until the test closes the
// release channel. It announces having entered, which is what makes "the
// sender is busy" an observable state rather than a timing assumption.
func blocking(t *testing.T) (sink *obs.MockSink, entered chan struct{}, release chan struct{}) {
	t.Helper()
	entered, release = make(chan struct{}, 8), make(chan struct{})
	sink = obs.NewMockSink(t)
	sink.EXPECT().Send(mock.Anything, mock.Anything).
		RunAndReturn(func(context.Context, []obs.Event) error {
			entered <- struct{}{}
			<-release
			return nil
		}).Maybe()
	return sink, entered, release
}

func newEmitter(t *testing.T, opts ...obs.EmitterOption) *obs.Emitter {
	t.Helper()
	e, err := obs.NewEmitter(clock.NewFake(base), "agent", opts...)
	require.NoError(t, err, "NewEmitter")
	// Every emitter owns a goroutine. go test -race runs the whole suite in one
	// process, so one that outlives its test outlives every test after it.
	t.Cleanup(func() { _ = e.Close(context.Background()) })
	return e
}

func TestEmitReachesTheSink(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	ctx := obs.WithCorrelationID(context.Background(), "7aQx-3Kf")
	e.Emit(ctx, obs.KindMandateConstructed, "assembled the checkout")

	batch := <-sent
	require.Len(t, batch, 1, "one Emit has to arrive as one event")
	got := batch[0]
	assert.Equal(t, obs.KindMandateConstructed, got.Kind)
	assert.Equal(t, "7aQx-3Kf", got.CorrelationID, "the emitter did not read it off the context")
	assert.Equal(t, "agent", got.Role)
	// From the injected clock, never time.Now. A wall-clock read here would be
	// untestable and would breach the rule forbidigo enforces.
	if !got.At.Equal(base) {
		t.Errorf("at = %s, want %s", got.At, base)
	}
}

func TestEmitRejectionCarriesTheCode(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	e.EmitRejection(context.Background(), "constraint_violated", "amount above the cap")

	batch := <-sent
	assert.Equal(t, obs.KindMandateRejected, batch[0].Kind, "EmitRejection produced some other kind")
	assert.Equal(t, "constraint_violated", batch[0].Code)
}

// TestEmitAttachesAnAmount proves WithAmount reaches the sink on a kind that
// accepts one, the way a call site like the merchant's settle handler needs.
func TestEmitAttachesAnAmount(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	price := generated.Amount{Amount: 18900, Currency: "USD"}
	e.Emit(context.Background(), obs.KindMandateVerified, "verified", obs.WithAmount(price))

	batch := <-sent
	require.NotNil(t, batch[0].Amount, "WithAmount did not reach the event")
	assert.Equal(t, price, *batch[0].Amount)
}

// TestEmitRejectionAttachesAnAmount is TestEmitAttachesAnAmount's counterpart
// for the other helper: the merchant's own quoted price on the refusal it
// wrote, the example issue #174 opens with — 210.00 refused against a 200.00
// cap.
func TestEmitRejectionAttachesAnAmount(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	quoted := generated.Amount{Amount: 21000, Currency: "USD"}
	e.EmitRejection(context.Background(), "constraint_violated", "amount above the cap", obs.WithAmount(quoted))

	batch := <-sent
	assert.Equal(t, obs.KindMandateRejected, batch[0].Kind)
	require.NotNil(t, batch[0].Amount, "WithAmount did not reach the rejection")
	assert.Equal(t, quoted, *batch[0].Amount)
}

// TestWithAmountOnADisallowedKindDropsTheWholeEvent pins the failure mode a
// caller gets wrong: WithAmount does not strip itself off a kind Validate
// refuses it on, it fails the whole event, the same way a stray Code would.
// EventOpt's own comment on the context-versus-parameter choice is what this
// pins — an amount that leaked from the wrong call would be caught here rather
// than silently rendering nothing.
func TestWithAmountOnADisallowedKindDropsTheWholeEvent(t *testing.T) {
	t.Parallel()

	sink, _ := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	e.Emit(context.Background(), obs.KindReceiptIssued, "receipt issued",
		obs.WithAmount(generated.Amount{Amount: 100, Currency: "USD"}))

	assert.Equal(t, 1, e.Stats().Rejected,
		"an amount on receipt_issued must fail Validate, not render as an event with no price")
	assert.Equal(t, 0, e.Stats().Emitted)
}

// TestEmitNeverBlocks is the constraint ADR 0003 states outright: a collector
// outage or a slow consumer must never delay a mandate or receipt operation.
//
// It runs inside a synctest bubble because that turns the failure from a hang
// into a result. If Emit ever waited on the sender, every goroutine in the
// bubble would be durably blocked and synctest fails the test immediately,
// rather than the suite sitting there until the package timeout.
func TestEmitNeverBlocks(t *testing.T) {
	synctest.Test(t, func(t *testing.T) {
		sink, entered, release := blocking(t)
		e, err := obs.NewEmitter(clock.NewFake(base), "agent",
			obs.WithSink(sink), obs.WithBuffer(4))
		require.NoError(t, err, "NewEmitter")

		// Get the sender parked inside Send, so nothing is draining.
		e.Emit(context.Background(), obs.KindMandateConstructed, "first")
		<-entered

		// Far more than the buffer holds. Every one of these has to return.
		for range 100 {
			e.Emit(context.Background(), obs.KindMandatePresented, "while the sink is stuck")
		}

		assert.Equal(t, 101, e.Stats().Emitted)
		assert.NotZero(t, e.Stats().Dropped, "nothing was dropped, so the buffer did not bound anything")

		close(release)
		assert.NoError(t, e.Close(context.Background()), "Close")
	})
}

// TestFullBufferDropsOldest pins which end goes. The tail is what belongs on
// screen, so the newest event must survive and the oldest must not.
func TestFullBufferDropsOldest(t *testing.T) {
	t.Parallel()

	sink, entered, release := blocking(t)
	e, err := obs.NewEmitter(clock.NewFake(base), "agent",
		obs.WithSink(sink), obs.WithBuffer(2))
	require.NoError(t, err, "NewEmitter")

	// Park the sender, which also empties the ring: it takes this event as a
	// batch before blocking.
	e.Emit(context.Background(), obs.KindMandateConstructed, "taken")
	<-entered

	// Ring holds two; the third evicts the first of them.
	e.Emit(context.Background(), obs.KindMandatePresented, "evicted")
	e.Emit(context.Background(), obs.KindMandateVerified, "kept")
	e.Emit(context.Background(), obs.KindReceiptIssued, "kept too")

	require.Equal(t, 1, e.Stats().Dropped, "the ring evicted the wrong number of events")

	close(release)
	require.NoError(t, e.Close(context.Background()), "Close")
	// Which events survived is not in question here, only how many, so assert
	// through the counters: four emitted, one dropped, three delivered. The
	// sink's own count is the other half — one batch parked, one on the drain.
	assert.Equal(t, obs.Stats{Emitted: 4, Dropped: 1, Delivered: 3}, e.Stats())
	sink.AssertNumberOfCalls(t, "Send", 2)
}

// TestCloseFlushes covers the events emitted just before shutdown. Losing them
// would mean the last thing that happened is the thing never shown.
func TestCloseFlushes(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	for range 10 {
		e.Emit(context.Background(), obs.KindReceiptIssued, "issued")
	}
	require.NoError(t, e.Close(context.Background()), "Close")

	assert.Len(t, delivered(sent), 10, "Close did not drain what was still buffered")
	assert.Equal(t, 10, e.Stats().Delivered)
}

func TestEmitAfterCloseIsADropNotAPanic(t *testing.T) {
	t.Parallel()

	sink, _ := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	require.NoError(t, e.Close(context.Background()), "Close")
	e.Emit(context.Background(), obs.KindMandateVerified, "after the door shut")

	assert.Equal(t, 1, e.Stats().Dropped)
	sink.AssertNotCalled(t, "Send", mock.Anything, mock.Anything)
	// Closing twice is what a defer plus an explicit call produces, and it must
	// not panic on the closed channel.
	assert.NoError(t, e.Close(context.Background()), "second Close")
}

func TestInvalidEventIsRejectedNotBuffered(t *testing.T) {
	t.Parallel()

	sink, _ := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink))

	// A kind outside the closed set. Nothing downstream could display it.
	e.Emit(context.Background(), obs.Kind("mandate_teleported"), "not a real moment")

	require.NoError(t, e.Close(context.Background()), "Close")
	s := e.Stats()
	assert.Equal(t, 1, s.Rejected)
	assert.Equal(t, 0, s.Emitted, "an invalid event was buffered")
	sink.AssertNotCalled(t, "Send", mock.Anything, mock.Anything)
}

// TestSinkFailureIsCountedNotRetried covers the decision not to retry. The log
// is never evidence, so a failed delivery costs a screenshot and nothing more —
// and a retry would be a queue whose failure modes outweigh what it protects.
func TestSinkFailureIsCountedNotRetried(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, errors.New("collector refused"))
	e := newEmitter(t, obs.WithSink(sink))

	e.Emit(context.Background(), obs.KindMandateConstructed, "first")
	<-sent

	require.NoError(t, e.Close(context.Background()), "Close")
	s := e.Stats()
	assert.Equal(t, 1, s.Failed)
	assert.Equal(t, 0, s.Delivered)
	// The whole of the decision, in one line: the sink was offered the batch
	// once and never again.
	sink.AssertNumberOfCalls(t, "Send", 1)
}

// TestDefaultSinkThrowsEventsAway is the case every role's unit tests hit: an
// emitter built with no sink at all, in a process where no collector exists.
func TestDefaultSinkThrowsEventsAway(t *testing.T) {
	t.Parallel()

	e := newEmitter(t)
	e.Emit(context.Background(), obs.KindMandateConstructed, "nobody is listening")

	require.NoError(t, e.Close(context.Background()), "Close")
	if got := e.Stats().Delivered; got != 1 {
		t.Errorf("Delivered = %d, want 1 — Discard should accept everything", got)
	}
}

func TestNewEmitterRejectsNonsense(t *testing.T) {
	t.Parallel()

	if _, err := obs.NewEmitter(nil, "agent"); err == nil {
		t.Error("an emitter with no clock was accepted")
	}
	if _, err := obs.NewEmitter(clock.NewFake(base), ""); err == nil {
		t.Error("an emitter with no role was accepted; its events would have no lane")
	}
	if _, err := obs.NewEmitter(clock.NewFake(base), "agent", obs.WithBuffer(0)); err == nil {
		t.Error("a zero buffer was accepted")
	}
	if _, err := obs.NewEmitter(clock.NewFake(base), "agent", obs.WithSink(nil)); err == nil {
		t.Error("a nil sink was accepted; it would panic on the first event")
	}
}

// TestCloseRespectsItsDeadline covers the caller that has run out of patience.
// Shutdown must not be held open by a screenshot feed.
func TestCloseRespectsItsDeadline(t *testing.T) {
	t.Parallel()

	sink, entered, release := blocking(t)
	e, err := obs.NewEmitter(clock.NewFake(base), "agent", obs.WithSink(sink))
	require.NoError(t, err, "NewEmitter")
	e.Emit(context.Background(), obs.KindMandateConstructed, "stuck in the sink")
	<-entered

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	assert.ErrorIs(t, e.Close(ctx), context.Canceled, "a cancelled Close has to say why it gave up")

	// Let the sender finish so the goroutine does not outlive the test.
	close(release)
	assert.NoError(t, e.Close(context.Background()), "Close after the sink released")
}

// TestConcurrentEmit exists for the race detector. Every request in a role
// emits, so a data race here is not theoretical.
func TestConcurrentEmit(t *testing.T) {
	t.Parallel()

	sink, sent := recording(t, nil)
	e := newEmitter(t, obs.WithSink(sink), obs.WithBuffer(1024))

	var wg sync.WaitGroup
	for i := range 50 {
		wg.Go(func() {
			ctx := obs.WithCorrelationID(context.Background(), "7aQx-3Kf")
			e.Emit(ctx, obs.KindMandatePresented, "concurrent")
			if i%2 == 0 {
				_ = e.Stats()
			}
		})
	}
	wg.Wait()

	require.NoError(t, e.Close(context.Background()), "Close")
	assert.Equal(t, 50, e.Stats().Emitted)
	// The mock is the other half of what -race is here to check: fifty
	// goroutines emitted, and the sink's own record of what arrived is kept
	// under testify's lock rather than one this test would have to hold.
	assert.Len(t, delivered(sent), 50, "an event emitted concurrently never reached the sink")
}

// TestANilEmitterIsAWorkingNoOp is what lets a role hold its emitter as an
// optional field rather than a required one.
//
// Every role Service does, and so does agent.Client. A nil receiver that
// panicked would put a crash in the middle of a verification path — turning a
// missing screenshot into a failed purchase, which is the one thing ADR 0003
// says emission may never do. It is the same decision Discard makes about a
// missing collector, one layer up.
func TestANilEmitterIsAWorkingNoOp(t *testing.T) {
	t.Parallel()

	var e *obs.Emitter

	assert.NotPanics(t, func() {
		e.Emit(t.Context(), obs.KindMandateVerified, "nobody is listening")
		e.EmitRejection(t.Context(), "mandate_expired", "nor to this")
		e.EmitEvent(obs.Event{Kind: obs.KindReceiptIssued, Role: "agent", At: base})
	}, "a role started without a collector must not panic where it verifies")

	assert.Zero(t, e.Stats(), "an emitter that does not exist has recorded nothing")
	assert.NoError(t, e.Close(t.Context()),
		"closing what was never opened is not a failure; a caller handed one should "+
			"not have to know whether there was anything to shut down")
}
