package transport_test

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/SkylinePlatform/agentic-payments/backend/internal/core/generated"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/clock"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/problem"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/store"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/transport"
)

var base = time.Date(2026, 8, 4, 12, 0, 0, 0, time.UTC)

// Every test in this file is ultimately about one number: how many times the
// wrapped handler actually ran. That number is now kept by
// transport.MockHandler, generated by mockery from net/http's Handler into
// mocks_test.go — see backend/.mockery.yml.
//
// The mock keeps it under its own lock, which is one fewer thing for this file
// to get right: TestRetryWhileTheFirstIsStillRunning drives the middleware
// from two goroutines at once, and the count it reads used to be an atomic
// this file had to remember to reach for.

// response describes an answer. It is not a double — it is the body, status
// and headers a handler writes — which is what lets "fail twice, then succeed"
// be two expectations on the mock rather than a field a test reaches in and
// mutates while the middleware is running.
type response struct {
	status int
	body   string
	// echoBody, when set, writes back what it read, which is how the tests
	// check the handler can still read a body the middleware already consumed.
	echoBody bool
	// headers are set before the status line, so a test can check what
	// survives a replay.
	headers map[string]string
}

// write answers as resp describes. The request body is read whether or not it
// is echoed back, because a handler that reads is the case the middleware has
// to survive.
func (resp response) write(w http.ResponseWriter, r *http.Request) {
	read, _ := io.ReadAll(r.Body)
	w.Header().Set("Content-Type", "application/json")
	for k, v := range resp.headers {
		w.Header().Set(k, v)
	}
	if resp.status != 0 {
		w.WriteHeader(resp.status)
	}
	if resp.echoBody {
		_, _ = w.Write(read)
		return
	}
	_, _ = w.Write([]byte(resp.body))
}

// handler returns a mock handler that answers every request with resp, however
// many times it is called — including not at all, which several of these tests
// are about.
func handler(t *testing.T, resp response) *transport.MockHandler {
	t.Helper()
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).Run(resp.write).Maybe()
	return h
}

// ran asserts how many times the handler was reached, and why that is the
// number.
//
// The count comes from AssertNumberOfCalls rather than len(h.Calls) because
// the mock guards its own call log, and one of these tests still has a request
// in flight on another goroutine when it asks. assert.True is what carries the
// reasoning, which AssertNumberOfCalls has no argument for.
//
// assert throughout, never require: a helper that calls require is one the
// next caller gets wrong from inside a wg.Go, and this file already has one of
// those.
func ran(t *testing.T, h *transport.MockHandler, times int, why string) {
	t.Helper()
	assert.True(t, h.AssertNumberOfCalls(t, "ServeHTTP", times), why)
}

func wrap(t *testing.T, h http.Handler, opts ...store.Option) (http.Handler, *clock.Fake) {
	t.Helper()
	c := clock.NewFake(base)
	m, err := transport.NewIdempotency(c, opts...)
	require.NoError(t, err, "NewIdempotency")
	return m.Wrap(h), c
}

func post(key, target, body string) *http.Request {
	r := httptest.NewRequest(http.MethodPost, target, strings.NewReader(body))
	if key != "" {
		r.Header.Set(transport.KeyHeader, key)
	}
	return r
}

// problemOf decodes a Problem Details body, failing if the response is not one.
func problemOf(t *testing.T, rec *httptest.ResponseRecorder) problem.Problem {
	t.Helper()
	if got := rec.Header().Get("Content-Type"); got != problem.ContentType {
		t.Fatalf("Content-Type = %q, want %q; body: %s", got, problem.ContentType, rec.Body)
	}
	var p problem.Problem
	if err := json.Unmarshal(rec.Body.Bytes(), &p); err != nil {
		t.Fatalf("decode problem: %v; body: %s", err, rec.Body)
	}
	return p
}

func TestSafeMethodsPassThrough(t *testing.T) {
	t.Parallel()

	for _, method := range []string{http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodTrace} {
		t.Run(method, func(t *testing.T) {
			t.Parallel()

			h := handler(t, response{body: `{"ok":true}`})
			wrapped, _ := wrap(t, h)

			rec := httptest.NewRecorder()
			wrapped.ServeHTTP(rec, httptest.NewRequest(method, "/checkout", nil))

			assert.Equal(t, http.StatusOK, rec.Code, "a safe method needs no key")
			ran(t, h, 1, "a safe method was not passed through")
		})
	}
}

func TestMissingKeyIsRejected(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("", "/checkout", `{"amount":100}`))

	if rec.Code != http.StatusBadRequest {
		t.Errorf("status = %d, want 400", rec.Code)
	}
	if p := problemOf(t, rec); p.Code != generated.ErrorCodeIdempotencyKeyMissing {
		t.Errorf("code = %q, want %q", p.Code, generated.ErrorCodeIdempotencyKeyMissing)
	}
	// The point of refusing rather than deduplicating on the body: the
	// operation must not have happened.
	ran(t, h, 0, "a request with no key reached the handler")
}

func TestRetryReplaysWithoutRerunning(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"receipt":"abc"}`})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))

	second := httptest.NewRecorder()
	wrapped.ServeHTTP(second, post("k1", "/checkout", `{"amount":100}`))

	ran(t, h, 1, "the retry re-executed the operation")
	if first.Body.String() != second.Body.String() {
		t.Errorf("replayed body %q, want %q", second.Body, first.Body)
	}
	if second.Code != first.Code {
		t.Errorf("replayed status %d, want %d", second.Code, first.Code)
	}
	if second.Header().Get("Content-Type") != "application/json" {
		t.Errorf("replay lost the content type: %q", second.Header().Get("Content-Type"))
	}
	if first.Header().Get(transport.ReplayedHeader) != "" {
		t.Error("the first response was marked as a replay")
	}
	if second.Header().Get(transport.ReplayedHeader) != "true" {
		t.Error("the replay was not marked, so an operator cannot tell the two apart")
	}
}

func TestSameKeyDifferentRequestConflicts(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name         string
		target, body string
	}{
		{"different body", "/checkout", `{"amount":999}`},
		{"different path", "/refund", `{"amount":100}`},
		// The query string is part of what makes a request that request. A
		// fingerprint blind to it would answer this with the first response.
		{"different query", "/checkout?currency=EUR", `{"amount":100}`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			h := handler(t, response{body: `{"ok":true}`})
			wrapped, _ := wrap(t, h)

			wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))

			rec := httptest.NewRecorder()
			wrapped.ServeHTTP(rec, post("k1", tc.target, tc.body))

			if rec.Code != http.StatusConflict {
				t.Errorf("status = %d, want 409", rec.Code)
			}
			if p := problemOf(t, rec); p.Code != generated.ErrorCodeIdempotencyConflict {
				t.Errorf("code = %q, want %q", p.Code, generated.ErrorCodeIdempotencyConflict)
			}
			ran(t, h, 1, "the conflicting request was executed")
		})
	}
}

// TestServerErrorIsNotRemembered covers the rule that a failed operation has
// not happened, so a retry must get another chance. Remembering a 500 would
// hand the caller a key that can never succeed until the window lapses.
func TestServerErrorIsNotRemembered(t *testing.T) {
	t.Parallel()

	// Two expectations rather than one handler whose fields the test rewrites
	// half way through: the first two attempts fail, the third succeeds, and
	// testify's cleanup fails the test if either count is wrong.
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(response{status: http.StatusInternalServerError, body: `{"error":"transient"}`}.write).Times(2)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(response{body: `{"receipt":"abc"}`}.write).Once()
	wrapped, _ := wrap(t, h)

	for range 2 {
		rec := httptest.NewRecorder()
		wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))
		if rec.Code != http.StatusInternalServerError {
			t.Fatalf("status = %d, want 500", rec.Code)
		}
	}
	ran(t, h, 2, "a transient failure was cached")

	// And once it succeeds, that is what gets remembered.
	for range 2 {
		wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	}
	ran(t, h, 3, "the success was not remembered")
}

// TestClientErrorIsRemembered is the other side of that rule: a 4xx is a
// settled answer about this request, and repeating it would not change it.
func TestClientErrorIsRemembered(t *testing.T) {
	t.Parallel()

	h := handler(t, response{status: http.StatusForbidden, body: `{"code":"constraint_violated"}`})
	wrapped, _ := wrap(t, h)

	for range 2 {
		rec := httptest.NewRecorder()
		wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))
		if rec.Code != http.StatusForbidden {
			t.Fatalf("status = %d, want 403", rec.Code)
		}
	}
	ran(t, h, 1, "a settled rejection was re-evaluated")
}

func TestHandlerStillReadsTheBody(t *testing.T) {
	t.Parallel()

	h := handler(t, response{echoBody: true})
	wrapped, _ := wrap(t, h)

	const body = `{"amount":100,"currency":"EUR"}`
	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", body))

	if rec.Body.String() != body {
		t.Errorf("handler saw %q, want %q — the middleware consumed the body without restoring it",
			rec.Body, body)
	}
}

func TestRecordLapses(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, c := wrap(t, h, store.WithWindow(time.Hour))

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	c.Advance(2 * time.Hour)
	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))

	ran(t, h, 2, "the key should be free past its window")
}

// TestCapacityRefusesBeforeTheOperationRuns is why the key is claimed up
// front. A store that cannot remember the answer cannot promise the operation
// will not run twice, and the only moment that promise can still be declined
// is before the operation happens.
func TestCapacityRefusesBeforeTheOperationRuns(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h, store.WithLimit(1))

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":1}`))

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k2", "/checkout", `{"amount":2}`))

	if rec.Code != http.StatusServiceUnavailable {
		t.Errorf("status = %d, want 503", rec.Code)
	}
	if p := problemOf(t, rec); p.Code != generated.ErrorCodeVerifierUnavailable {
		t.Errorf("code = %q, want %q", p.Code, generated.ErrorCodeVerifierUnavailable)
	}
	ran(t, h, 1, "an operation ran that could not be remembered")
}

// TestRetryWhileTheFirstIsStillRunning is the case a lookup-then-remember
// middleware waves through. A client whose request times out retries while the
// original is still in the handler; if both are allowed to proceed, the
// operation happens twice, which is the whole thing this middleware exists to
// prevent.
func TestRetryWhileTheFirstIsStillRunning(t *testing.T) {
	t.Parallel()

	resp := response{body: `{"receipt":"abc"}`}
	entered, release := make(chan struct{}), make(chan struct{})

	// Only the first request parks. A handler that blocked every run would
	// turn a middleware that wrongly admits the second request into a test
	// that deadlocks rather than one that fails, and a hang says far less than
	// an assertion does — so the holding is one expectation and everything
	// after it is another.
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(func(w http.ResponseWriter, r *http.Request) {
			entered <- struct{}{}
			<-release
			resp.write(w, r)
		}).Once()
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).Run(resp.write).Maybe()
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	var wg sync.WaitGroup
	wg.Go(func() { wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`)) })

	<-entered // the first request is inside the handler and holding the key

	retry := httptest.NewRecorder()
	wrapped.ServeHTTP(retry, post("k1", "/checkout", `{"amount":100}`))

	if retry.Code != http.StatusConflict {
		t.Errorf("status = %d, want 409", retry.Code)
	}
	if p := problemOf(t, retry); p.Code != generated.ErrorCodeIdempotencyInFlight {
		t.Errorf("code = %q, want %q", p.Code, generated.ErrorCodeIdempotencyInFlight)
	}

	close(release)
	wg.Wait()

	ran(t, h, 1, "the retry re-executed an operation still in flight")

	// Once the original finishes, the same retry replays instead of running.
	after := httptest.NewRecorder()
	wrapped.ServeHTTP(after, post("k1", "/checkout", `{"amount":100}`))
	ran(t, h, 1, "the operation ran again once the first one had finished")
	if after.Body.String() != first.Body.String() {
		t.Errorf("replayed %q, want %q", after.Body, first.Body)
	}
}

// TestPanickingHandlerFreesTheKey covers the same rule on the path that does
// not return normally. net/http recovers a handler panic per connection, so
// the key has to be given back while unwinding or it is stranded for the
// window.
func TestPanickingHandlerFreesTheKey(t *testing.T) {
	t.Parallel()

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic("handler exploded")
	})
	c := clock.NewFake(base)
	m, err := transport.NewIdempotency(c)
	require.NoError(t, err, "NewIdempotency")

	func() {
		defer func() { _ = recover() }()
		m.Wrap(panicking).ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	}()

	h := handler(t, response{body: `{"ok":true}`})
	rec := httptest.NewRecorder()
	m.Wrap(h).ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))

	assert.Equal(t, http.StatusOK, rec.Code, "the panicking attempt stranded the key")
	ran(t, h, 1, "the key was still held by the attempt that panicked")
}

// TestReplayKeepsEveryHeader covers the fidelity claim. A 201 whose Location
// header vanished on replay is not the answer the first caller got, and a
// client following it would be sent nowhere.
func TestReplayKeepsEveryHeader(t *testing.T) {
	t.Parallel()

	h := handler(t, response{
		status:  http.StatusCreated,
		body:    `{"receipt":"abc"}`,
		headers: map[string]string{"Location": "/receipts/abc", "ETag": `"v1"`},
	})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))

	second := httptest.NewRecorder()
	wrapped.ServeHTTP(second, post("k1", "/checkout", `{"amount":100}`))

	for _, name := range []string{"Location", "ETag", "Content-Type"} {
		if got, want := second.Header().Get(name), first.Header().Get(name); got != want {
			t.Errorf("replayed %s = %q, want %q", name, got, want)
		}
	}
	if second.Code != http.StatusCreated {
		t.Errorf("replayed status = %d, want 201", second.Code)
	}
}

// TestOversizedBodyIsRejectedAsSuch covers the status the caller is owed. A
// body over the cap is not malformed — it parses fine and is simply larger
// than this endpoint reads — and answering 400 would send its sender looking
// for a syntax error that is not there.
func TestOversizedBodyIsRejectedAsSuch(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", strings.Repeat("x", (1<<20)+1)))

	if rec.Code != http.StatusRequestEntityTooLarge {
		t.Errorf("status = %d, want 413", rec.Code)
	}
	if p := problemOf(t, rec); p.Code != generated.ErrorCodeRequestTooLarge {
		t.Errorf("code = %q, want %q", p.Code, generated.ErrorCodeRequestTooLarge)
	}
	ran(t, h, 0, "an oversized body reached the handler")
}

// TestOversizedResponseIsNotRemembered covers the cap on the other side. The
// caller still gets the whole answer; what is given up is the remembered copy,
// because holding an unbounded response for the whole retention window turns a
// bound on record count into no bound on memory.
func TestOversizedResponseIsNotRemembered(t *testing.T) {
	t.Parallel()

	big := strings.Repeat("x", (1<<20)+1)
	h := handler(t, response{body: big})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))
	if first.Body.Len() != len(big) {
		t.Fatalf("the caller got %d bytes, want %d — the cap truncated the real answer",
			first.Body.Len(), len(big))
	}

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	ran(t, h, 2, "an oversized response was remembered anyway")
}

// TestFlushReachesTheUnderlyingWriter guards an optional interface that
// wrapping a ResponseWriter drops by default. Losing it does not fail a test
// that only reads the finished body — it fails a streaming handler in
// production, quietly.
func TestFlushReachesTheUnderlyingWriter(t *testing.T) {
	t.Parallel()

	flushed := make(chan struct{}, 1)
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		f, ok := w.(http.Flusher)
		if !ok {
			t.Error("the handler was given a writer that cannot flush")
			return
		}
		_, _ = w.Write([]byte(`{"partial":true}`))
		f.Flush()
		flushed <- struct{}{}
	})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))

	select {
	case <-flushed:
	default:
		t.Fatal("the handler never reached its flush")
	}
	if !rec.Flushed {
		t.Error("the flush did not reach the underlying writer")
	}
}

// TestHijackIsNotRemembered is the test the Hijack/Unwrap pair exists to make
// pass, and it fails the moment recorder.hijacked stops being consulted.
//
// After a hijack nothing the handler sends passes through the recorder, so the
// recorder still holds the 200 and the empty body it was built with. Recording
// that would replay an answer nobody gave: the second request below would never
// reach the handler and would be given that empty 200 instead of the upgrade it
// asked for. Counting handler runs is therefore the assertion — comparing the
// two responses would pass even with the bug present, because what a hijacked
// connection sends is not the recorder's to compare.
func TestHijackIsNotRemembered(t *testing.T) {
	t.Parallel()

	var runs atomic.Int64
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		runs.Add(1)
		// assert, not require: this runs on the server's goroutine, where
		// FailNow is not legal.
		conn, buf, err := http.NewResponseController(w).Hijack()
		if !assert.NoError(t, err, "the handler could not hijack through the middleware") {
			return
		}
		defer func() { assert.NoError(t, conn.Close(), "close the hijacked connection") }()
		// Written on the raw connection, so none of it reaches the recorder.
		_, err = buf.WriteString("HTTP/1.1 101 Switching Protocols\r\nUpgrade: demo\r\nConnection: Upgrade\r\n\r\n")
		assert.NoError(t, err, "write the upgrade response")
		assert.NoError(t, buf.Flush(), "flush the upgrade response")
	})

	m, err := transport.NewIdempotency(clock.NewFake(base))
	require.NoError(t, err, "NewIdempotency")
	srv := httptest.NewServer(m.Wrap(h))
	defer srv.Close()

	upgrade := func() int {
		req, err := http.NewRequestWithContext(t.Context(), http.MethodPost, srv.URL,
			strings.NewReader(`{"amount":100}`))
		require.NoError(t, err, "build the request")
		req.Header.Set(transport.KeyHeader, "k1")
		resp, err := srv.Client().Do(req)
		require.NoError(t, err, "the request failed")
		require.NoError(t, resp.Body.Close(), "close the response body")
		return resp.StatusCode
	}

	assert.Equal(t, http.StatusSwitchingProtocols, upgrade(),
		"the first upgrade did not reach the handler")
	assert.Equal(t, http.StatusSwitchingProtocols, upgrade(),
		"the second upgrade was answered from the store — the empty 200 a hijack leaves behind")
	assert.Equal(t, int64(2), runs.Load(),
		"a hijacked response was remembered, so the retry never re-ran the handler")
}

// TestResponseControllerReachesTheUnderlyingWriter pins what Unwrap buys. The
// recorder does not implement deadlines and never will; without Unwrap,
// http.ResponseController cannot find the writer that does, and every such call
// fails with ErrNotSupported for no reason the handler can see.
func TestResponseControllerReachesTheUnderlyingWriter(t *testing.T) {
	t.Parallel()

	deadline := make(chan error, 1)
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		deadline <- http.NewResponseController(w).SetWriteDeadline(time.Time{})
		w.WriteHeader(http.StatusOK)
	})

	m, err := transport.NewIdempotency(clock.NewFake(base))
	require.NoError(t, err, "NewIdempotency")
	srv := httptest.NewServer(m.Wrap(h))
	defer srv.Close()

	req, err := http.NewRequestWithContext(t.Context(), http.MethodPost, srv.URL, strings.NewReader(`{}`))
	require.NoError(t, err, "build the request")
	req.Header.Set(transport.KeyHeader, "k1")
	resp, err := srv.Client().Do(req)
	require.NoError(t, err, "the request failed")
	require.NoError(t, resp.Body.Close(), "close the response body")

	assert.NoError(t, <-deadline, "the recorder hid a capability the real writer has")
}
