package transport_test

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/SkylinePlatform/agentic-payments/backend/internal/core/generated"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/clock"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/problem"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/store"
	"github.com/SkylinePlatform/agentic-payments/backend/internal/platform/transport"
)

var base = time.Date(2026, 8, 4, 12, 0, 0, 0, time.UTC)

// Every test in this file is ultimately about one number: how many times the
// wrapped handler actually ran. That number is now kept by
// transport.MockHandler, generated by mockery from net/http's Handler into
// mocks_test.go — see backend/.mockery.yml.
//
// The mock keeps it under its own lock, which is one fewer thing for this file
// to get right: TestRetryWhileTheFirstIsStillRunning drives the middleware
// from two goroutines at once, and the count it reads used to be an atomic
// this file had to remember to reach for.

// response describes an answer. It is not a double — it is the body, status
// and headers a handler writes — which is what lets "fail twice, then succeed"
// be two expectations on the mock rather than a field a test reaches in and
// mutates while the middleware is running.
type response struct {
	status int
	body   string
	// echoBody, when set, writes back what it read, which is how the tests
	// check the handler can still read a body the middleware already consumed.
	echoBody bool
	// headers are set before the status line, so a test can check what
	// survives a replay.
	headers map[string]string
}

// write answers as resp describes. The request body is read whether or not it
// is echoed back, because a handler that reads is the case the middleware has
// to survive.
func (resp response) write(w http.ResponseWriter, r *http.Request) {
	read, _ := io.ReadAll(r.Body)
	w.Header().Set("Content-Type", "application/json")
	for k, v := range resp.headers {
		w.Header().Set(k, v)
	}
	if resp.status != 0 {
		w.WriteHeader(resp.status)
	}
	if resp.echoBody {
		_, _ = w.Write(read)
		return
	}
	_, _ = w.Write([]byte(resp.body))
}

// handler returns a mock handler that answers every request with resp, however
// many times it is called — including not at all, which several of these tests
// are about.
func handler(t *testing.T, resp response) *transport.MockHandler {
	t.Helper()
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).Run(resp.write).Maybe()
	return h
}

// ran asserts how many times the handler was reached, and why that is the
// number.
//
// The count comes from AssertNumberOfCalls rather than len(h.Calls) because
// the mock guards its own call log, and one of these tests still has a request
// in flight on another goroutine when it asks. assert.True is what carries the
// reasoning, which AssertNumberOfCalls has no argument for.
//
// assert throughout, never require: a helper that calls require is one the
// next caller gets wrong from inside a wg.Go, and this file already has one of
// those.
func ran(t *testing.T, h *transport.MockHandler, times int, why string) {
	t.Helper()
	assert.True(t, h.AssertNumberOfCalls(t, "ServeHTTP", times), why)
}

func wrap(t *testing.T, h http.Handler, opts ...store.Option) (http.Handler, *clock.Fake) {
	t.Helper()
	c := clock.NewFake(base)
	m, err := transport.NewIdempotency(c, opts...)
	require.NoError(t, err, "NewIdempotency")
	return m.Wrap(h), c
}

func post(key, target, body string) *http.Request {
	r := httptest.NewRequest(http.MethodPost, target, strings.NewReader(body))
	if key != "" {
		r.Header.Set(transport.KeyHeader, key)
	}
	return r
}

// problemOf decodes a Problem Details body, failing if the response is not one.
//
// assert, for the reason ran gives: this is a helper, and the call site that
// gets it wrong is the one that has not been written yet. The early return is
// what "cannot continue" looks like without FailNow — a caller then reads .Code
// off the zero Problem and adds a second failure, which is noise next to a
// failure that was never reported at all.
func problemOf(t *testing.T, rec *httptest.ResponseRecorder) problem.Problem {
	t.Helper()
	var p problem.Problem
	if !assert.Equalf(t, problem.ContentType, rec.Header().Get("Content-Type"),
		"a rejection a client cannot recognise as Problem Details is one it has to guess at; body: %s",
		rec.Body) {
		return p
	}
	assert.NoErrorf(t, json.Unmarshal(rec.Body.Bytes(), &p),
		"a caller reading .Code off a body that did not decode is asserting nothing; body: %s", rec.Body)
	return p
}

func TestSafeMethodsPassThrough(t *testing.T) {
	t.Parallel()

	for _, method := range []string{http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodTrace} {
		t.Run(method, func(t *testing.T) {
			t.Parallel()

			h := handler(t, response{body: `{"ok":true}`})
			wrapped, _ := wrap(t, h)

			rec := httptest.NewRecorder()
			wrapped.ServeHTTP(rec, httptest.NewRequest(method, "/checkout", nil))

			assert.Equal(t, http.StatusOK, rec.Code, "a safe method needs no key")
			ran(t, h, 1, "a safe method was not passed through")
		})
	}
}

func TestMissingKeyIsRejected(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("", "/checkout", `{"amount":100}`))

	assert.Equal(t, http.StatusBadRequest, rec.Code,
		"a missing key is the caller's to fix, and a 5xx would invite them to retry it unchanged")
	assert.Equal(t, generated.ErrorCodeIdempotencyKeyMissing, problemOf(t, rec).Code,
		"the code is what names the header, and 400 alone does not")
	// The point of refusing rather than deduplicating on the body: the
	// operation must not have happened.
	ran(t, h, 0, "a request with no key reached the handler")
}

func TestRetryReplaysWithoutRerunning(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"receipt":"abc"}`})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))

	second := httptest.NewRecorder()
	wrapped.ServeHTTP(second, post("k1", "/checkout", `{"amount":100}`))

	ran(t, h, 1, "the retry re-executed the operation")
	assert.Equal(t, first.Body.String(), second.Body.String(),
		"a retry is owed the answer the operation already produced, not a second opinion")
	assert.Equal(t, first.Code, second.Code, "the status is part of that answer")
	assert.Equal(t, "application/json", second.Header().Get("Content-Type"),
		"a replay a client cannot parse is not the answer the first caller got")
	assert.Empty(t, first.Header().Get(transport.ReplayedHeader),
		"marking the original a replay would make the header mean nothing")
	assert.Equal(t, "true", second.Header().Get(transport.ReplayedHeader),
		"the two are identical by design, so without the header an operator cannot tell them apart")
}

func TestSameKeyDifferentRequestConflicts(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name         string
		target, body string
	}{
		{"different body", "/checkout", `{"amount":999}`},
		{"different path", "/refund", `{"amount":100}`},
		// The query string is part of what makes a request that request. A
		// fingerprint blind to it would answer this with the first response.
		{"different query", "/checkout?currency=EUR", `{"amount":100}`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			h := handler(t, response{body: `{"ok":true}`})
			wrapped, _ := wrap(t, h)

			wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))

			rec := httptest.NewRecorder()
			wrapped.ServeHTTP(rec, post("k1", tc.target, tc.body))

			assert.Equal(t, http.StatusConflict, rec.Code,
				"answering anything else would hand this request the other one's result")
			assert.Equal(t, generated.ErrorCodeIdempotencyConflict, problemOf(t, rec).Code,
				"a reused key and a busy key are both 409, and only the code separates them")
			ran(t, h, 1, "the conflicting request was executed")
		})
	}
}

// TestServerErrorIsNotRemembered covers the rule that a failed operation has
// not happened, so a retry must get another chance. Remembering a 500 would
// hand the caller a key that can never succeed until the window lapses.
func TestServerErrorIsNotRemembered(t *testing.T) {
	t.Parallel()

	// Two expectations rather than one handler whose fields the test rewrites
	// half way through: the first two attempts fail, the third succeeds, and
	// testify's cleanup fails the test if either count is wrong.
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(response{status: http.StatusInternalServerError, body: `{"error":"transient"}`}.write).Times(2)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(response{body: `{"receipt":"abc"}`}.write).Once()
	wrapped, _ := wrap(t, h)

	for range 2 {
		rec := httptest.NewRecorder()
		wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))
		require.Equal(t, http.StatusInternalServerError, rec.Code,
			"the run count below only means what it says if both attempts failed")
	}
	ran(t, h, 2, "a transient failure was cached")

	// And once it succeeds, that is what gets remembered.
	for range 2 {
		wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	}
	ran(t, h, 3, "the success was not remembered")
}

// TestClientErrorIsRemembered is the other side of that rule: a 4xx is a
// settled answer about this request, and repeating it would not change it.
func TestClientErrorIsRemembered(t *testing.T) {
	t.Parallel()

	h := handler(t, response{status: http.StatusForbidden, body: `{"code":"constraint_violated"}`})
	wrapped, _ := wrap(t, h)

	for range 2 {
		rec := httptest.NewRecorder()
		wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))
		require.Equal(t, http.StatusForbidden, rec.Code,
			"the second answer is only a replay of the first if the first was the rejection")
	}
	ran(t, h, 1, "a settled rejection was re-evaluated")
}

func TestHandlerStillReadsTheBody(t *testing.T) {
	t.Parallel()

	h := handler(t, response{echoBody: true})
	wrapped, _ := wrap(t, h)

	const body = `{"amount":100,"currency":"EUR"}`
	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", body))

	assert.Equal(t, body, rec.Body.String(),
		"the handler echoes what it read, so a difference here is the body the middleware consumed and did not restore")
}

func TestRecordLapses(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, c := wrap(t, h, store.WithWindow(time.Hour))

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	c.Advance(2 * time.Hour)
	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))

	ran(t, h, 2, "the key should be free past its window")
}

// TestCapacityRefusesBeforeTheOperationRuns is why the key is claimed up
// front. A store that cannot remember the answer cannot promise the operation
// will not run twice, and the only moment that promise can still be declined
// is before the operation happens.
func TestCapacityRefusesBeforeTheOperationRuns(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h, store.WithLimit(1))

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":1}`))

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k2", "/checkout", `{"amount":2}`))

	assert.Equal(t, http.StatusServiceUnavailable, rec.Code,
		"a store with no room is the verifier's problem, and the caller is owed a status that says come back")
	assert.Equal(t, generated.ErrorCodeVerifierUnavailable, problemOf(t, rec).Code,
		"the key is still the caller's to reuse, which a capacity code says and a conflict would deny")
	ran(t, h, 1, "an operation ran that could not be remembered")
}

// TestRetryWhileTheFirstIsStillRunning is the case a lookup-then-remember
// middleware waves through. A client whose request times out retries while the
// original is still in the handler; if both are allowed to proceed, the
// operation happens twice, which is the whole thing this middleware exists to
// prevent.
func TestRetryWhileTheFirstIsStillRunning(t *testing.T) {
	t.Parallel()

	resp := response{body: `{"receipt":"abc"}`}
	entered, release := make(chan struct{}), make(chan struct{})

	// Only the first request parks. A handler that blocked every run would
	// turn a middleware that wrongly admits the second request into a test
	// that deadlocks rather than one that fails, and a hang says far less than
	// an assertion does — so the holding is one expectation and everything
	// after it is another.
	h := transport.NewMockHandler(t)
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).
		Run(func(w http.ResponseWriter, r *http.Request) {
			entered <- struct{}{}
			<-release
			resp.write(w, r)
		}).Once()
	h.EXPECT().ServeHTTP(mock.Anything, mock.Anything).Run(resp.write).Maybe()
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	var wg sync.WaitGroup
	wg.Go(func() { wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`)) })

	<-entered // the first request is inside the handler and holding the key

	retry := httptest.NewRecorder()
	wrapped.ServeHTTP(retry, post("k1", "/checkout", `{"amount":100}`))

	// assert, though these two do run on the test goroutine and FailNow would
	// be legal here. The first request is parked on <-release, and aborting
	// before the close below strands it: the failure would be reported, and
	// then the test that reported it would be the one holding a goroutine open.
	// Getting to the close is worth more than stopping early, which is what the
	// t.Errorf these replaced was already saying.
	assert.Equal(t, http.StatusConflict, retry.Code,
		"letting the retry through is how one payment becomes two")
	assert.Equal(t, generated.ErrorCodeIdempotencyInFlight, problemOf(t, retry).Code,
		"this retry should be sent back later, where the conflict code tells a caller not to bother")

	close(release)
	wg.Wait()

	ran(t, h, 1, "the retry re-executed an operation still in flight")

	// Once the original finishes, the same retry replays instead of running.
	after := httptest.NewRecorder()
	wrapped.ServeHTTP(after, post("k1", "/checkout", `{"amount":100}`))
	ran(t, h, 1, "the operation ran again once the first one had finished")
	assert.Equal(t, first.Body.String(), after.Body.String(),
		"the caller who was refused mid-flight is owed the same answer as the one who waited")
}

// TestPanickingHandlerFreesTheKey covers the same rule on the path that does
// not return normally. net/http recovers a handler panic per connection, so
// the key has to be given back while unwinding or it is stranded for the
// window.
func TestPanickingHandlerFreesTheKey(t *testing.T) {
	t.Parallel()

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic("handler exploded")
	})
	c := clock.NewFake(base)
	m, err := transport.NewIdempotency(c)
	require.NoError(t, err, "NewIdempotency")

	func() {
		defer func() { _ = recover() }()
		m.Wrap(panicking).ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	}()

	h := handler(t, response{body: `{"ok":true}`})
	rec := httptest.NewRecorder()
	m.Wrap(h).ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))

	assert.Equal(t, http.StatusOK, rec.Code, "the panicking attempt stranded the key")
	ran(t, h, 1, "the key was still held by the attempt that panicked")
}

// TestReplayKeepsEveryHeader covers the fidelity claim. A 201 whose Location
// header vanished on replay is not the answer the first caller got, and a
// client following it would be sent nowhere.
func TestReplayKeepsEveryHeader(t *testing.T) {
	t.Parallel()

	h := handler(t, response{
		status:  http.StatusCreated,
		body:    `{"receipt":"abc"}`,
		headers: map[string]string{"Location": "/receipts/abc", "ETag": `"v1"`},
	})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))

	second := httptest.NewRecorder()
	wrapped.ServeHTTP(second, post("k1", "/checkout", `{"amount":100}`))

	for _, name := range []string{"Location", "ETag", "Content-Type"} {
		assert.Equalf(t, first.Header().Get(name), second.Header().Get(name),
			"%s did not survive the replay, so the second caller was not given the answer the first one got",
			name)
	}
	assert.Equal(t, http.StatusCreated, second.Code,
		"a 201 replayed as anything else tells the second caller the resource was never created")
}

// TestOversizedBodyIsRejectedAsSuch covers the status the caller is owed. A
// body over the cap is not malformed — it parses fine and is simply larger
// than this endpoint reads — and answering 400 would send its sender looking
// for a syntax error that is not there.
func TestOversizedBodyIsRejectedAsSuch(t *testing.T) {
	t.Parallel()

	h := handler(t, response{body: `{"ok":true}`})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", strings.Repeat("x", (1<<20)+1)))

	assert.Equal(t, http.StatusRequestEntityTooLarge, rec.Code,
		"400 would send the sender looking for a syntax error that is not there")
	assert.Equal(t, generated.ErrorCodeRequestTooLarge, problemOf(t, rec).Code,
		"the code is what tells the sender to send less rather than to fix what it sent")
	ran(t, h, 0, "an oversized body reached the handler")
}

// TestOversizedResponseIsNotRemembered covers the cap on the other side. The
// caller still gets the whole answer; what is given up is the remembered copy,
// because holding an unbounded response for the whole retention window turns a
// bound on record count into no bound on memory.
func TestOversizedResponseIsNotRemembered(t *testing.T) {
	t.Parallel()

	big := strings.Repeat("x", (1<<20)+1)
	h := handler(t, response{body: big})
	wrapped, _ := wrap(t, h)

	first := httptest.NewRecorder()
	wrapped.ServeHTTP(first, post("k1", "/checkout", `{"amount":100}`))
	require.Equal(t, len(big), first.Body.Len(),
		"the cap may give up the remembered copy and never the answer itself, so a short body here "+
			"makes the run count below a test of the wrong thing")

	wrapped.ServeHTTP(httptest.NewRecorder(), post("k1", "/checkout", `{"amount":100}`))
	ran(t, h, 2, "an oversized response was remembered anyway")
}

// TestFlushReachesTheUnderlyingWriter guards an optional interface that
// wrapping a ResponseWriter drops by default. Losing it does not fail a test
// that only reads the finished body — it fails a streaming handler in
// production, quietly.
func TestFlushReachesTheUnderlyingWriter(t *testing.T) {
	t.Parallel()

	flushed := make(chan struct{}, 1)
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		f, ok := w.(http.Flusher)
		// assert, not require: a handler is a callback. This one happens to be
		// called on the test goroutine, because nothing here starts a server —
		// but the two tests below serve theirs from httptest.NewServer, where
		// the identical line would be running on net/http's goroutine and
		// FailNow would not be legal. Nothing about it would look different.
		if !assert.True(t, ok, "wrapping a ResponseWriter drops Flusher unless the wrapper reimplements it") {
			return
		}
		_, _ = w.Write([]byte(`{"partial":true}`))
		f.Flush()
		flushed <- struct{}{}
	})
	wrapped, _ := wrap(t, h)

	rec := httptest.NewRecorder()
	wrapped.ServeHTTP(rec, post("k1", "/checkout", `{"amount":100}`))

	// The send is the last line of the handler, so an empty channel means the
	// handler returned early and the flush below would be proving nothing.
	require.Len(t, flushed, 1, "the handler never reached its flush")
	assert.True(t, rec.Flushed,
		"a flush that stops at the wrapper is invisible until a stream stalls in production")
}

// TestHijackIsNotRemembered is the test the Hijack/Unwrap pair exists to make
// pass, and it fails the moment recorder.hijacked stops being consulted.
//
// After a hijack nothing the handler sends passes through the recorder, so the
// recorder still holds the 200 and the empty body it was built with. Recording
// that would replay an answer nobody gave: the second request below would never
// reach the handler and would be given that empty 200 instead of the upgrade it
// asked for. Counting handler runs is therefore the assertion — comparing the
// two responses would pass even with the bug present, because what a hijacked
// connection sends is not the recorder's to compare.
//
// # Why the second request waits for a channel and not for the client
//
// Issue #128 is what this cost when it did not. A hijacking handler answers on
// the raw connection, so the client is holding a complete 101 while the
// middleware is still unwinding — and the key is given back by a deferred
// Release that has not run yet. A second request sent on the strength of the
// first client call having returned is racing that unwind, and when it loses it
// is told 409 idempotency_in_flight and the handler does not run: the two
// numbers this test then reports are the ones a remembered hijack would
// produce, so the flake was indistinguishable from the bug being looked for.
//
// The middleware exposes nothing that says when a key is free, and it should
// not: a caller cannot act on the answer, and a method that reported it would
// be an invitation to poll. The ordering comes from wrapping instead. Release is
// deferred inside the guarded handler, so it has run by the time ServeHTTP
// returns to the wrapper below, which is before the send on settled — a real
// happens-before edge, where a sleep would only have been a longer guess.
//
// TestAHijackKeepsItsKeyWhileItRuns is the other half: the 409 the flake saw is
// the correct answer to a request that arrives inside that window, not a defect
// that got covered over here.
func TestHijackIsNotRemembered(t *testing.T) {
	t.Parallel()

	var runs atomic.Int64
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		runs.Add(1)
		// assert, not require: this runs on the server's goroutine, where
		// FailNow is not legal.
		conn, buf, err := http.NewResponseController(w).Hijack()
		if !assert.NoError(t, err, "the handler could not hijack through the middleware") {
			return
		}
		defer func() { assert.NoError(t, conn.Close(), "close the hijacked connection") }()
		// Written on the raw connection, so none of it reaches the recorder.
		_, err = buf.WriteString("HTTP/1.1 101 Switching Protocols\r\nUpgrade: demo\r\nConnection: Upgrade\r\n\r\n")
		assert.NoError(t, err, "write the upgrade response")
		assert.NoError(t, buf.Flush(), "flush the upgrade response")
	})

	m, err := transport.NewIdempotency(clock.NewFake(base))
	require.NoError(t, err, "NewIdempotency")

	// Buffered for both requests, so that a failure which stops the test early
	// cannot leave a handler parked on the send — that would hang srv.Close in
	// wg.Wait and turn a failing test into one that never reports.
	settled := make(chan struct{}, 2)
	guarded := m.Wrap(h)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		guarded.ServeHTTP(w, r)
		settled <- struct{}{}
	}))
	defer srv.Close()

	upgrade := func() int {
		req, err := http.NewRequestWithContext(t.Context(), http.MethodPost, srv.URL,
			strings.NewReader(`{"amount":100}`))
		require.NoError(t, err, "build the request")
		req.Header.Set(transport.KeyHeader, "k1")
		resp, err := srv.Client().Do(req)
		require.NoError(t, err, "the request failed")
		require.NoError(t, resp.Body.Close(), "close the response body")
		return resp.StatusCode
	}

	assert.Equal(t, http.StatusSwitchingProtocols, upgrade(),
		"the first upgrade did not reach the handler")
	<-settled // the middleware has unwound, so the key is back before the retry
	assert.Equal(t, http.StatusSwitchingProtocols, upgrade(),
		"the second upgrade was answered from the store — the empty 200 a hijack leaves behind")
	<-settled
	assert.Equal(t, int64(2), runs.Load(),
		"a hijacked response was remembered, so the retry never re-ran the handler")
}

// TestAHijackKeepsItsKeyWhileItRuns pins the answer a request gets inside the
// window the test above steps over, because #128 spent a CI run and an
// investigation on mistaking it for a bug.
//
// A hijacked connection belongs to the handler until it returns, which for the
// upgrades a hijack is used for is the life of the stream. The key stays claimed
// for exactly that long, so a second request presenting it is refused as
// in-flight — the attempt really has not finished — and told to come back rather
// than told it made a mistake. What it must never be given is the empty 200 the
// recorder is holding, which is the failure TestHijackIsNotRemembered names.
//
// # The window is not unique to hijack, only unbounded there
//
// Worth stating, because the tidier sentence — Complete runs inside the handler
// chain, before net/http writes the terminating bytes, so no client can hold a
// complete answer while the key is claimed — is true of the plain case and too
// strong as a rule. A handler that sets Content-Length, flushes and then keeps
// working has already given its client the whole answer, and a retry arriving
// before it returns is answered 409 here too; measured, not reasoned. What
// hijack changes is duration: an ordinary handler's gap ends when it returns,
// a hijacked one's lasts as long as the stream. Nothing in this repository is
// in the first shape — the only flushing handler is the collector's SSE stream,
// which is a GET and never reaches this middleware — and if one were, the
// answer below would still be the true one for it.
//
// Nothing here is timed. The first handler is parked on a channel the test
// closes, so the key is provably still held when the second request arrives.
func TestAHijackKeepsItsKeyWhileItRuns(t *testing.T) {
	t.Parallel()

	var runs atomic.Int64
	release := make(chan struct{})
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		runs.Add(1)
		// assert, not require: the server's goroutine, where FailNow is not legal.
		conn, buf, err := http.NewResponseController(w).Hijack()
		if !assert.NoError(t, err, "the handler could not hijack through the middleware") {
			return
		}
		defer func() { assert.NoError(t, conn.Close(), "close the hijacked connection") }()
		_, err = buf.WriteString("HTTP/1.1 101 Switching Protocols\r\nUpgrade: demo\r\nConnection: Upgrade\r\n\r\n")
		assert.NoError(t, err, "write the upgrade response")
		assert.NoError(t, buf.Flush(), "flush the upgrade response")
		<-release
	})

	m, err := transport.NewIdempotency(clock.NewFake(base))
	require.NoError(t, err, "NewIdempotency")
	srv := httptest.NewServer(m.Wrap(h))
	// LIFO: the parked handler is freed first, so srv.Close has something to
	// wait for rather than something to wait on forever — including when an
	// assertion below stops the test before the last line.
	defer srv.Close()
	defer close(release)

	do := func() (int, string) {
		req, err := http.NewRequestWithContext(t.Context(), http.MethodPost, srv.URL,
			strings.NewReader(`{"amount":100}`))
		require.NoError(t, err, "build the request")
		req.Header.Set(transport.KeyHeader, "k1")
		resp, err := srv.Client().Do(req)
		require.NoError(t, err, "the request failed")
		defer func() { assert.NoError(t, resp.Body.Close(), "close the response body") }()

		// The body of a 101 is the upgraded connection, which the handler above
		// holds until this test releases it. Reading it waits for the stream to
		// end, and the stream ends when this test does — so asking for it is a
		// deadlock, not a slow read.
		if resp.StatusCode == http.StatusSwitchingProtocols {
			return resp.StatusCode, ""
		}
		body, err := io.ReadAll(resp.Body)
		require.NoError(t, err, "read the response body")
		return resp.StatusCode, string(body)
	}

	status, _ := do()
	require.Equal(t, http.StatusSwitchingProtocols, status,
		"the stream this test parks has to have started, or the key below is held by nothing")

	status, body := do()
	assert.Equal(t, http.StatusConflict, status,
		"a stream still running is an attempt still running, and its key is not free")

	var p problem.Problem
	assert.NoErrorf(t, json.Unmarshal([]byte(body), &p),
		"a caller reading .Code off a body that did not decode is asserting nothing; body: %s", body)
	assert.Equal(t, generated.ErrorCodeIdempotencyInFlight, p.Code,
		"in-flight tells the caller to come back; a conflict would tell it to correct a request that was right")
	assert.Equal(t, int64(1), runs.Load(),
		"a second stream was opened under a key the first one still holds")
}

// TestResponseControllerReachesTheUnderlyingWriter pins what Unwrap buys. The
// recorder does not implement deadlines and never will; without Unwrap,
// http.ResponseController cannot find the writer that does, and every such call
// fails with ErrNotSupported for no reason the handler can see.
func TestResponseControllerReachesTheUnderlyingWriter(t *testing.T) {
	t.Parallel()

	deadline := make(chan error, 1)
	h := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		deadline <- http.NewResponseController(w).SetWriteDeadline(time.Time{})
		w.WriteHeader(http.StatusOK)
	})

	m, err := transport.NewIdempotency(clock.NewFake(base))
	require.NoError(t, err, "NewIdempotency")
	srv := httptest.NewServer(m.Wrap(h))
	defer srv.Close()

	req, err := http.NewRequestWithContext(t.Context(), http.MethodPost, srv.URL, strings.NewReader(`{}`))
	require.NoError(t, err, "build the request")
	req.Header.Set(transport.KeyHeader, "k1")
	resp, err := srv.Client().Do(req)
	require.NoError(t, err, "the request failed")
	require.NoError(t, resp.Body.Close(), "close the response body")

	assert.NoError(t, <-deadline, "the recorder hid a capability the real writer has")
}
