package constraint_test

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/SkylinePlatform/agentic-payments/backend/internal/core/authz/constraint"
)

// The conformance suite for the constraint renderer.
//
// # Why a golden file rather than the table in render_test.go
//
// TestRenderSaysWhatTheUserIsSigning already pins sentences, and it is enough
// while Go is the only thing that renders one. It stopped being enough when a
// second implementation appeared: frontend/src/constraint/render.ts renders
// constraints in the Mandate Inspector, which decodes a mandate signed some time
// ago with no live surface to ask, and in the console, which shows what a prompt
// would authorise before anything is signed. Neither has a signature in it,
// which is what makes a TypeScript renderer legitimate at all — the consent path
// keeps asking the surface, because the sentence the user reads has to be the
// sentence the signature covers.
//
// Two renderers means the sentence is now an interoperable artefact rather than
// one package's output, and this file is what stops them drifting. Go owns
// contracts/testdata/render_vectors.json: the table below is the source, the
// file is generated from it, and TypeScript only reads. So a change to Render()
// with no regeneration fails here, in the language that made the change, rather
// than in a suite one directory tree away.
//
// AGENTS.md's rule for widening `make vectors` beyond adapters/ and pkg/ is
// "something in core/ that a second implementation has to reproduce". This is
// that thing, and the Makefile was widened to match.

// goldenPath is the vector file, relative to this package. `go test` runs with
// the package directory as its working directory, so this resolves the same way
// from `make`, from CI and from an editor.
const goldenPath = "../../../../../contracts/testdata/render_vectors.json"

// update rewrites the vector file from the table below.
//
//	go test ./internal/core/authz/constraint -run TestGoldenRenderVectors -update
//
// A flag rather than an environment variable so that it shows up in `go test
// -args -h` beside the toolchain's own, and so that a stray export cannot
// silently turn a comparison into a rewrite.
var update = flag.Bool("update", false, "rewrite the render vectors from the renderer")

// renderVector is one sentence, and the constraint that produces it.
type renderVector struct {
	// Name identifies the vector. The TypeScript suite names a handful of these
	// directly, so they are part of the file's contract rather than labels.
	Name string `json:"name"`

	// Note says what this vector is here to catch, where that is not obvious
	// from the sentence. Read by people, not by either suite.
	Note string `json:"note,omitempty"`

	// Constraint is the node as it arrives on a mandate.
	Constraint json.RawMessage `json:"constraint"`

	// Rendered is what Render() says about it. "an unparsed constraint" is the
	// answer for every node Parse refuses, which is not a placeholder: it is
	// what a caller gets from the zero Expression that Parse returns beside its
	// error, and what a surface handed one must print rather than crash.
	Rendered string `json:"rendered"`
}

// renderVectorFile is the whole document.
type renderVectorFile struct {
	Comment string         `json:"$comment"`
	Vectors []renderVector `json:"vectors"`
}

const fileComment = "Generated by TestGoldenRenderVectors in " +
	"backend/internal/core/authz/constraint/golden_render_test.go. Do not hand-edit: the Go table " +
	"is the source, and this file is regenerated from it with `go test ./internal/core/authz/constraint " +
	"-run TestGoldenRenderVectors -update`. Read by that test and by " +
	"frontend/src/constraint/render.test.ts, which is the second implementation these sentences pin."

// unparsed is the sentence every refused node renders as.
const unparsed = "an unparsed constraint"

// vectors is the table. Each entry is one constraint as it would arrive on a
// mandate, and Render's sentence for it is computed rather than written down —
// which is the point of generating the file rather than hand-writing it.
//
// The set is chosen so that every rule the two renderers have to agree on is
// covered by at least one entry that fails when that rule is broken. Where the
// entry exists to catch one specific mistake, the note says which.
var vectors = []struct {
	name string
	note string
	raw  string
}{
	{
		name: "built-scenario",
		note: "Beat 3 of the built scenario, whole: the sentence the Trusted Surface shows and the user signs.",
		raw: `{"op":"all","of":[
			{"op":"lte","field":"amount","value":{"amount":20000,"currency":"USD"}},
			{"op":"within","field":"at","value":{"from":"2026-06-01T00:00:00Z","to":"2026-08-31T23:59:59Z"}},
			{"op":"eq","field":"item.attr.route.origin","value":"BEG"},
			{"op":"eq","field":"item.attr.route.destination","value":"PMI"}]}`,
	},

	// --- money is string surgery on the integer ---------------------------

	{
		name: "amount-cap",
		raw:  `{"op":"lte","field":"amount","value":{"amount":18900,"currency":"USD"}}`,
	},
	{
		name: "amount-under-one-unit",
		note: "The zero-pad. A renderer that divided and trimmed would print 0.07 too, but one that sliced without padding prints .07 or crashes.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":7,"currency":"EUR"}}`,
	},
	{
		name: "amount-at-a-thousand",
		note: "No thousands separator. Intl.NumberFormat gives $1,000.00 here, which is why the TypeScript renderer may not reuse formatAmount.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":100000,"currency":"USD"}}`,
	},
	{
		name: "amount-zero",
		note: "A zero-amount authorisation is how an instrument is verified without charging it, so this is a real value and not an edge case.",
		raw:  `{"op":"eq","field":"amount","value":{"amount":0,"currency":"USD"}}`,
	},
	{
		name: "amount-in-a-currency-with-no-minor-unit",
		note: "A known limitation, pinned rather than fixed: renderMoney hardcodes two minor digits, so 189 JPY reads as 1.89 JPY where it should read as 189 JPY. Both renderers are wrong in the same way on purpose — the amount is never wrong, only its presentation, and the fix is a minor-unit table that contracts/instrument/amount.json already implies somebody will need. Do not make this vector agree with Intl, which gives the right answer here and the wrong one at amount-at-a-thousand.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":189,"currency":"JPY"}}`,
	},
	{
		name: "amount-negative-is-refused",
		note: "A mandate authorises a payment; money moving the other way is a refund, which is a different object with a different authorisation. renderMoney carries a sign branch that no constraint can reach through Render — in Go it is reachable only through the rejection reason, where the subject's own amount is rendered.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":-500,"currency":"USD"}}`,
	},
	{
		name: "money-list",
		note: "Mixed currencies parse: which currency a purchase is in is not known when the mandate is signed, so the mismatch surfaces at evaluation and never here.",
		raw:  `{"op":"in","field":"amount","value":[{"amount":20000,"currency":"USD"},{"amount":10000,"currency":"EUR"}]}`,
	},
	{
		name: "money-band",
		raw:  `{"op":"between","field":"amount","value":{"from":{"amount":10000,"currency":"USD"},"to":{"amount":20000,"currency":"USD"}}}`,
	},

	// --- numbers ----------------------------------------------------------

	{
		name: "quantity-cap",
		raw:  `{"op":"lte","field":"quantity","value":2}`,
	},
	{
		name: "number-negative",
		note: "The sign on a plain number, which money's zero-pad does not cover.",
		raw:  `{"op":"gte","field":"quantity","value":-3}`,
	},

	// --- text: folded for labels, exact for identifiers -------------------

	{
		name: "label-is-folded",
		note: "Text values are normalised when the constraint is parsed, not when it is rendered. A renderer reading the raw JSON prints `  Flights  `.",
		raw:  `{"op":"eq","field":"item.category","value":"  Flights  "}`,
	},
	{
		name: "label-is-folded-beyond-ascii",
		note: "The fold is a full Unicode lower-casing in both languages, not an ASCII one.",
		raw:  `{"op":"eq","field":"item.category","value":"Café"}`,
	},
	{
		name: "item-identifier-keeps-its-case",
		note: "item.id is exact. Whether two spellings name the same thing is the identifier scheme's business, and folding would decide it on the scheme's behalf.",
		raw:  `{"op":"eq","field":"item.id","value":"GTIN:05012345678900"}`,
	},
	{
		name: "merchant-identifier-keeps-its-case",
		raw:  `{"op":"eq","field":"merchant.id","value":"Air-Serbia"}`,
	},
	{
		name: "identifier-with-surrounding-space",
		note: "Even an exact identifier loses surrounding space: that is transport noise, not identity.",
		raw:  `{"op":"eq","field":"item.id","value":"  iata:JU324  "}`,
	},
	{
		name: "label-with-whitespace-only-one-language-trims",
		note: "U+0085 is whitespace to Go's TrimSpace and not to JavaScript's trim; U+00A0 is whitespace to both. A renderer using trim() unaided keeps the U+0085 and shows a label the verifier folded away.",
		raw:  `{"op":"eq","field":"item.category","value":"\u0085Flights\u00a0"}`,
	},
	{
		name: "text-with-a-quote",
		note: "Go renders text with %q and TypeScript with JSON.stringify; this is where the two would part company if either hand-rolled the escaping.",
		raw:  `{"op":"eq","field":"item.id","value":"sku:\"odd\""}`,
	},
	{
		name: "text-with-escapes-only-go-writes",
		note: "%q and JSON.stringify agree on everything printable and part company below it: Go writes \\a, \\v and \\x01 where JSON writes \\u escapes, and escapes U+007F where JSON passes it through. Nobody types this; that is why it would go unnoticed.",
		raw:  `{"op":"eq","field":"item.id","value":"sku:\u0007\u000b\u0001\u007f"}`,
	},
	{
		name: "text-with-an-unprintable-rune-past-ascii",
		note: "%q escapes anything outside Unicode's L, M, N, P and S categories plus the ASCII space, so an interior non-breaking space becomes \\u00a0 where JSON.stringify would print it as itself.",
		raw:  `{"op":"eq","field":"merchant.category","value":"Air\u00a0Serbia"}`,
	},
	{
		name: "text-list",
		raw:  `{"op":"in","field":"item.category","value":["flights","hotels"]}`,
	},
	{
		name: "text-exclusion",
		raw:  `{"op":"nin","field":"merchant.category","value":["casino"]}`,
	},

	// --- item attributes derive their noun --------------------------------

	{
		name: "item-attribute-noun",
		note: "The noun comes from the addressed name with dots turned into spaces, and the value is folded like any other label.",
		raw:  `{"op":"eq","field":"item.attr.route.origin","value":"BEG"}`,
	},
	{
		name: "item-attribute-noun-runs-deep",
		note: "Every dot, not only the first. core does not know what a flight is, so an attribute name is whatever the mandate wrote.",
		raw:  `{"op":"eq","field":"item.attr.seat.preference.window","value":"AISLE"}`,
	},
	{
		name: "item-attribute-with-one-segment",
		raw:  `{"op":"neq","field":"item.attr.fare","value":"basic"}`,
	},

	// --- dates: the wall clock as written, never a local one --------------

	{
		name: "time-window",
		raw:  `{"op":"within","field":"at","value":{"from":"2026-06-01T00:00:00Z","to":"2026-08-31T23:59:59Z"}}`,
	},
	{
		name: "time-at-the-utc-day-boundary",
		note: "The most valuable vector in the set. Go formats this instant in the zone it was parsed in, which for a Z timestamp is UTC, and says 31 August 2026. A TypeScript renderer reaching for new Date(x).getDate() reads the reader's own zone: east of Greenwich it says 1 September 2026 and the user is shown a window a day longer than the one they signed.",
		raw:  `{"op":"before","field":"at","value":"2026-08-31T23:59:59Z"}`,
	},
	{
		name: "time-with-a-positive-offset",
		note: "The other half of the same trap, and the half a machine in UTC would otherwise miss. The instant is 2026-08-31T22:30:00Z, so getUTCDate — the obvious fix for the vector above — says 31 August. Go says 1 September, because Format renders the wall clock in the offset the timestamp carried. No ambient timezone makes both this vector and time-at-the-utc-day-boundary pass a Date-based renderer: the first needs a non-positive offset and this one needs at least +01:30.",
		raw:  `{"op":"before","field":"at","value":"2026-09-01T00:30:00+02:00"}`,
	},
	{
		name: "time-with-a-negative-offset",
		note: "The same again from the other side: the instant is 2026-09-01T04:30:00Z, and the wall clock as written is 31 August.",
		raw:  `{"op":"after","field":"at","value":"2026-08-31T23:30:00-05:00"}`,
	},
	{
		name: "time-single-digit-day",
		note: "Go's `2` verb does not pad, so a renderer padding to two digits says 05 March.",
		raw:  `{"op":"before","field":"at","value":"2026-03-05T00:00:00Z"}`,
	},
	{
		name: "time-with-a-fraction",
		note: "Sub-second precision parses and then disappears: a user approving a booking window thinks in days.",
		raw:  `{"op":"before","field":"at","value":"2026-12-24T09:41:07.123456Z"}`,
	},
	{
		name: "time-list",
		raw:  `{"op":"in","field":"at","value":["2026-06-01T00:00:00Z","2026-07-01T00:00:00Z"]}`,
	},
	{
		name: "time-in-a-leap-year",
		raw:  `{"op":"before","field":"at","value":"2028-02-29T00:00:00Z"}`,
	},

	// --- groups -----------------------------------------------------------

	{
		name: "either-of-three",
		raw: `{"op":"any","of":[
			{"op":"eq","field":"item.category","value":"flights"},
			{"op":"eq","field":"item.category","value":"trains"},
			{"op":"eq","field":"item.category","value":"coaches"}]}`,
	},
	{
		name: "negation",
		raw:  `{"op":"not","of":[{"op":"eq","field":"merchant.category","value":"casino"}]}`,
	},
	{
		name: "nesting",
		raw: `{"op":"all","of":[
			{"op":"lte","field":"amount","value":{"amount":50000,"currency":"USD"}},
			{"op":"any","of":[
				{"op":"eq","field":"item.category","value":"flights"},
				{"op":"eq","field":"item.category","value":"trains"}]}]}`,
	},
	{
		name: "nesting-at-the-limit",
		note: "MaxDepth is 8 and the root is depth 0, so nine levels is the deepest thing that parses. The sentence is absurd; that it renders at all is the point.",
		raw:  nested(9),
	},
	{
		name: "nesting-past-the-limit-is-refused",
		note: "Ten levels. A verifier evaluates this on the request path against input it did not write, so the recursion is bounded by something other than good intentions — and the bound has to be the same number in both languages or one of them renders a constraint the other refuses.",
		raw:  nested(10),
	},

	// --- every operator says itself, mirroring TestEveryOperatorCanSayItself.
	// TestGoldenRenderVectorsCoverEveryOperator holds this list to the operator
	// table, so an operator added without a vector fails here.

	{name: "operator-eq", raw: `{"op":"eq","field":"item.category","value":"flights"}`},
	{name: "operator-neq", raw: `{"op":"neq","field":"item.category","value":"flights"}`},
	{name: "operator-lt", raw: `{"op":"lt","field":"quantity","value":5}`},
	{name: "operator-lte", raw: `{"op":"lte","field":"quantity","value":5}`},
	{name: "operator-gt", raw: `{"op":"gt","field":"quantity","value":5}`},
	{name: "operator-gte", raw: `{"op":"gte","field":"quantity","value":5}`},
	{name: "operator-in", raw: `{"op":"in","field":"item.category","value":["flights"]}`},
	{name: "operator-nin", raw: `{"op":"nin","field":"item.category","value":["flights"]}`},
	{name: "operator-between", raw: `{"op":"between","field":"quantity","value":{"from":1,"to":5}}`},
	{
		name: "operator-within",
		raw:  `{"op":"within","field":"at","value":{"from":"2026-06-01T00:00:00Z","to":"2026-08-31T00:00:00Z"}}`,
	},
	{name: "operator-before", raw: `{"op":"before","field":"at","value":"2026-06-01T00:00:00Z"}`},
	{name: "operator-after", raw: `{"op":"after","field":"at","value":"2026-06-01T00:00:00Z"}`},
	{name: "operator-all", raw: `{"op":"all","of":[{"op":"eq","field":"item.category","value":"flights"}]}`},
	{name: "operator-any", raw: `{"op":"any","of":[{"op":"eq","field":"item.category","value":"flights"}]}`},
	{name: "operator-not", raw: `{"op":"not","of":[{"op":"eq","field":"item.category","value":"flights"}]}`},

	// --- what a renderer must refuse to say -------------------------------
	//
	// A field or an operator the verifier does not know is rejected, never
	// skipped, and a renderer is where that first becomes visible to a person.
	// A second renderer that was more permissive than the verifier would put a
	// sentence on the screen for a limit nobody will enforce.

	{
		name: "unparsed-unknown-field",
		note: "The registry is closed. `price` is not `amount`, and a renderer that guessed would show a limit the verifier rejects as constraint_type_unknown.",
		raw:  `{"op":"lte","field":"price","value":{"amount":20000,"currency":"USD"}}`,
	},
	{
		name: "unparsed-unknown-operator",
		raw:  `{"op":"resembles","field":"item.category","value":"flights"}`,
	},
	{
		name: "unparsed-operator-does-not-fit-the-field",
		note: "Is Belgrade less than Palma has no answer anybody meant to ask, so ordering on text is refused when the mandate is read.",
		raw:  `{"op":"lt","field":"item.category","value":"flights"}`,
	},
	{
		name: "unparsed-leaf-with-no-field",
		raw:  `{"op":"eq","value":"flights"}`,
	},
	{
		name: "unparsed-leaf-carrying-children",
		raw:  `{"op":"eq","field":"item.category","value":"flights","of":[{"op":"eq","field":"item.id","value":"x"}]}`,
	},
	{
		name: "unparsed-group-with-no-children",
		note: "`all` of nothing is vacuously true and would permit every purchase; `any` of nothing would refuse them all. Neither is something a person meant to sign.",
		raw:  `{"op":"all","of":[]}`,
	},
	{
		name: "unparsed-group-carrying-a-field",
		raw:  `{"op":"any","field":"item.category","of":[{"op":"eq","field":"item.category","value":"flights"}]}`,
	},
	{
		name: "unparsed-not-with-two-children",
		note: "`not` over several children has two readings — none of them, or not all of them — and picking one silently would make a mandate mean something its author did not choose.",
		raw: `{"op":"not","of":[
			{"op":"eq","field":"item.category","value":"flights"},
			{"op":"eq","field":"item.category","value":"hotels"}]}`,
	},
	{
		name: "unparsed-empty-list",
		raw:  `{"op":"in","field":"item.category","value":[]}`,
	},
	{
		name: "unparsed-list-where-a-single-value-belongs",
		raw:  `{"op":"eq","field":"item.category","value":["flights"]}`,
	},
	{
		name: "unparsed-inverted-range",
		note: "An inverted range permits nothing, ever. Two values swapped is a far likelier explanation than an intent to authorise nothing.",
		raw:  `{"op":"between","field":"quantity","value":{"from":6,"to":2}}`,
	},
	{
		name: "unparsed-range-with-a-third-bound",
		raw:  `{"op":"between","field":"quantity","value":{"from":1,"to":5,"step":2}}`,
	},
	{
		name: "unparsed-fractional-quantity",
		note: "A count, not a measurement.",
		raw:  `{"op":"lte","field":"quantity","value":2.5}`,
	},
	{
		name: "unparsed-quantity-as-a-string",
		note: "Two wire representations of one claim means the looser arrives from whichever encoder was sloppiest.",
		raw:  `{"op":"lte","field":"quantity","value":"5"}`,
	},
	{
		name: "unparsed-quantity-past-the-exact-integer-ceiling",
		note: "2^53. Above it a JSON number has already lost precision before either language saw it, and refusing loudly beats comparing something quietly wrong.",
		raw:  `{"op":"lte","field":"quantity","value":9007199254740992}`,
	},
	{
		name: "unparsed-amount-with-an-unknown-key",
		note: "The unknown-operator rule one level down: a value carrying a key this verifier does not understand may not mean what the reader thinks it does.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":20000,"currency":"USD","net":true}}`,
	},
	{
		name: "unparsed-currency-not-iso-4217",
		note: "The shape contracts/instrument/amount.json states, ^[A-Z]{3}$. Lower case is not merely untidy — accepting it here would make a renderer show a limit the verifier will not read.",
		raw:  `{"op":"lte","field":"amount","value":{"amount":20000,"currency":"usd"}}`,
	},
	{
		name: "unparsed-amount-without-a-currency",
		raw:  `{"op":"lte","field":"amount","value":{"amount":20000}}`,
	},
	{
		name: "unparsed-timestamp-is-a-date-only",
		note: "RFC 3339, not ISO 8601's looser shapes.",
		raw:  `{"op":"before","field":"at","value":"2026-08-31"}`,
	},
	{
		name: "unparsed-timestamp-with-lowercase-designators",
		note: "RFC 3339 permits `t` and `z` in lower case; Go's time.RFC3339 layout does not, so this verifier does not either. A TypeScript regex written with the /i flag would accept it and render a limit Go refuses.",
		raw:  `{"op":"before","field":"at","value":"2026-08-31t23:59:59z"}`,
	},
	{
		name: "unparsed-timestamp-day-out-of-range",
		raw:  `{"op":"before","field":"at","value":"2026-02-30T00:00:00Z"}`,
	},
	{
		name: "unparsed-timestamp-is-not-a-string",
		raw:  `{"op":"before","field":"at","value":1780000000}`,
	},
	{
		name: "unparsed-text-is-not-a-string",
		raw:  `{"op":"eq","field":"item.category","value":42}`,
	},
	{
		name: "unparsed-text-is-empty",
		raw:  `{"op":"eq","field":"item.category","value":"   "}`,
	},
	{
		name: "unparsed-item-attribute-with-no-name",
		note: "`item.attr.` addresses nothing. The open half of the vocabulary is a rule, not an absence of one.",
		raw:  `{"op":"eq","field":"item.attr.","value":"BEG"}`,
	},
	{
		name: "unparsed-leaf-with-no-value",
		raw:  `{"op":"eq","field":"item.category"}`,
	},
}

// nested builds a chain of `not` groups depth levels deep, ending in a leaf.
//
// The leaf is one of the levels, so nested(9) produces nodes at depths 0 to 8 —
// exactly MaxDepth — and nested(10) is the first one Parse refuses.
func nested(depth int) string {
	node := `{"op":"eq","field":"item.category","value":"flights"}`
	for i := 1; i < depth; i++ {
		node = `{"op":"not","of":[` + node + `]}`
	}
	return node
}

// render produces the file from the table.
func render(t *testing.T) renderVectorFile {
	t.Helper()

	out := renderVectorFile{Comment: fileComment, Vectors: make([]renderVector, 0, len(vectors))}
	seen := make(map[string]struct{}, len(vectors))

	for _, v := range vectors {
		_, duplicate := seen[v.name]
		require.False(t, duplicate, "two vectors are named %q; the TypeScript suite selects by name", v.name)
		seen[v.name] = struct{}{}

		// The error is deliberately dropped rather than checked here. Parse
		// returns the zero Expression beside it, and rendering that is exactly
		// what a surface handed an unreadable constraint does — so one code
		// path covers both halves of the table, and the assertion that the two
		// halves are not mixed up lives in TestGoldenRenderVectorsRefuseWhatTheyClaimTo.
		expression, _ := constraint.Parse(node(t, v.raw))

		out.Vectors = append(out.Vectors, renderVector{
			Name:       v.name,
			Note:       v.note,
			Constraint: json.RawMessage(v.raw),
			Rendered:   expression.Render(),
		})
	}
	return out
}

// encode is the file's exact bytes. MarshalIndent re-indents the raw constraint
// bodies too, so the table may hold them formatted for reading.
func encode(t *testing.T, doc renderVectorFile) []byte {
	t.Helper()

	out, err := json.MarshalIndent(doc, "", "  ")
	require.NoError(t, err, "encoding the vectors")
	return append(out, '\n')
}

// vectorSummary is a vector with its constraint flattened to one line.
//
// It exists for the failure message rather than for the comparison: two
// json.RawMessage values that differ print as a hex dump of both, and the
// difference between an indented constraint and the same constraint on one line
// fills a screen while saying nothing. Flattening also makes the comparison the
// right one — the table writes its constraints across several lines for reading
// and the file holds them indented, and neither is a fact about the renderer.
type vectorSummary struct {
	Name       string
	Note       string
	Constraint string
	Rendered   string
}

func summarise(t *testing.T, vs []renderVector) []vectorSummary {
	t.Helper()

	out := make([]vectorSummary, 0, len(vs))
	for _, v := range vs {
		var flat bytes.Buffer
		require.NoError(t, json.Compact(&flat, v.Constraint), "compacting the constraint of %s", v.Name)
		out = append(out, vectorSummary{
			Name:       v.Name,
			Note:       v.Note,
			Constraint: flat.String(),
			Rendered:   v.Rendered,
		})
	}
	return out
}

// TestGoldenRenderVectors is the whole of the cross-language contract: the file
// on disk must be what this renderer produces.
//
// It compares the decoded vectors first and the bytes second, because the two
// failures want different fixes. A sentence that changed is a decision about
// what a user reads, and the assertion prints which one; a byte difference with
// identical vectors is formatting, and only needs the file regenerating.
func TestGoldenRenderVectors(t *testing.T) {
	t.Parallel()

	want := render(t)

	if *update {
		require.NoError(t, os.WriteFile(goldenPath, encode(t, want), 0o644), "rewriting the vectors")
		t.Logf("wrote %d vectors to %s", len(want.Vectors), goldenPath)
		return
	}

	raw, err := os.ReadFile(goldenPath)
	require.NoError(t, err, "reading the vectors; run this test with -update to create the file")
	require.NotEmpty(t, raw, "the vector file is empty, which no comparison below would notice")

	var got renderVectorFile
	require.NoError(t, json.Unmarshal(raw, &got), "decoding the vectors")

	assert.Equal(t, summarise(t, want.Vectors), summarise(t, got.Vectors),
		"the sentences on disk are not the ones this renderer produces; if the change to Render was "+
			"intended, regenerate with -update and read the diff as a change to what a user is shown")
	assert.Equal(t, string(encode(t, want)), string(raw),
		"the file's formatting has drifted from what -update writes, which would make every "+
			"regeneration show a spurious diff")
}

// TestGoldenRenderVectorsCoverEveryOperator holds the file to the operator
// table.
//
// TestEveryOperatorCanSayItself already proves each operator produces a sentence
// with no gap in it. This proves the *cross-language* suite sees each one: an
// operator added to the table with a phrase, and no vector, would be rendered by
// Go and by nothing else, and the two implementations could disagree about it
// indefinitely.
//
// It reads the file rather than the table above, so deleting a vector from the
// file fails here as well as in the byte comparison — a suite over a file is
// only as good as the file.
func TestGoldenRenderVectorsCoverEveryOperator(t *testing.T) {
	t.Parallel()

	named := make(map[string]struct{})
	for _, v := range onDisk(t).Vectors {
		named[v.Name] = struct{}{}
	}

	for _, op := range constraint.OperatorNames() {
		_, ok := named["operator-"+op]
		assert.True(t, ok,
			"no vector named operator-%s; the operator renders in Go and is unchecked in every other implementation", op)
	}
}

// TestGoldenRenderVectorsRefuseWhatTheyClaimTo checks that the two halves of the
// table have not been mixed up.
//
// Every vector whose sentence is "an unparsed constraint" must be one Parse
// actually refuses, and every other vector must be one it accepts. Without this
// a constraint that quietly stopped parsing — a field renamed, an operand rule
// tightened — would regenerate to the fallback sentence and the file would
// still be self-consistent, having silently lost whatever the vector proved.
func TestGoldenRenderVectorsRefuseWhatTheyClaimTo(t *testing.T) {
	t.Parallel()

	for _, v := range onDisk(t).Vectors {
		t.Run(v.Name, func(t *testing.T) {
			t.Parallel()

			_, err := constraint.Parse(node(t, string(v.Constraint)))
			if v.Rendered == unparsed {
				assert.Error(t, err,
					"this vector says the constraint cannot be read, and Parse read it")
				return
			}
			assert.NoError(t, err,
				"this vector carries a sentence, so it has to be a constraint a verifier can read")
			assert.False(t, strings.Contains(v.Rendered, "  ") || strings.HasSuffix(v.Rendered, " "),
				"the sentence has a gap in it where a phrase should be: %q", v.Rendered)
		})
	}
}

// onDisk reads the vector file, and is where the read is proved rather than
// assumed: an empty or wrongly-rooted path would make the two tests above pass
// over nothing.
func onDisk(t *testing.T) renderVectorFile {
	t.Helper()

	raw, err := os.ReadFile(goldenPath)
	require.NoError(t, err, "reading the vectors from %s", goldenPath)

	var doc renderVectorFile
	require.NoError(t, json.Unmarshal(raw, &doc), "decoding the vectors")
	require.NotEmpty(t, doc.Vectors, "the vector file carries no vectors, and every check over it would pass")
	return doc
}
