package merchant

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The two paths this file reaches, from this package's directory.
const (
	shippedCataloguePath = "../../../../deploy/catalogue.json"
	publicDir            = "../../../../frontend/public"
	derivedPrefix        = "/images/catalogue/derived/"
)

// derivedNote is tools/catalogue/mark.go's own comment block, character for
// character.
//
// It is the one part of the picture the two implementations legitimately
// disagree about — see liveMarkNote — so it is what this test hands markSVG to
// make the rest of the comparison exact. Writing it out here is not a second
// copy of anything load-bearing: if it drifts from what that program writes,
// the committed file it is compared against carries the other text and this
// test fails, which is precisely the drift it exists to catch.
func derivedNote(id string) string {
	return "    Generated by tools/catalogue from " + id + ". Do not hand-edit: `make\n" +
		"    catalogue` rewrites every file in this directory. The colours are the\n" +
		"    light-theme tokens frontend/src/styles.css declares, as literal hex.\n"
}

// TestALiveMarkIsTheMarkThisShopAlreadyDraws is what makes a duplicated drawing
// safe rather than merely small.
//
// tools/catalogue draws sixty pictures into frontend/public and commits them;
// this package draws one per fetched offer at start-up and carries it inside the
// offer. The two cannot share code — tools/catalogue is a separate Go module and
// a `package main`, so nothing here can import it and nothing there can import
// this — so the shelf reading as one shop rests on two implementations agreeing.
//
// This is the agreement, measured rather than asserted: every derived picture in
// the repository is re-drawn here and compared byte for byte. A change to either
// side fails in Go, on the branch that made it, instead of showing up as a table
// where half the rows came out of a different program.
//
// It is deliberately not a golden file of its own. The committed SVGs *are* the
// vectors, they are already regenerated by `make catalogue`, and a second copy
// beside this test would be a third thing to keep in step.
func TestALiveMarkIsTheMarkThisShopAlreadyDraws(t *testing.T) {
	t.Parallel()

	f, err := LoadCatalogue(shippedCataloguePath)
	require.NoError(t, err, "the shipped catalogue has to load, or there is nothing to compare against")

	compared := 0
	for _, offer := range f.Offers {
		if !strings.HasPrefix(offer.ImageURL, derivedPrefix) {
			continue
		}
		compared++

		committed, err := os.ReadFile(filepath.Join(publicDir, offer.ImageURL))
		require.NoError(t, err, "a derived picture the catalogue names is missing from the tree")

		assert.Equal(t, string(committed), string(markSVG(offer.ID, offer.Title, derivedNote(offer.ID))),
			"this package's drawing has drifted from tools/catalogue's, so the fetched half of the "+
				"shelf and the derived half would no longer read as one shop")
	}

	require.Greater(t, compared, 40,
		"nothing was compared, so this test proves nothing — the derived pictures have moved or "+
			"been renamed and the loop above quietly matched no offer")
}

// TestALiveOffersPictureTravelsWithIt is the property the image rule now rests
// on, stated directly rather than through Validate.
//
// A root-relative path is a promise that a file exists somewhere else, and issue
// #215 is the pull request about what happens when it does not. A data URI makes
// no such promise: it is the picture. So the assertions are that it decodes,
// that what comes out is the SVG this package draws, and that it names the offer
// it belongs to — which together mean a row cannot render a broken image without
// the offer itself being broken.
func TestALiveOffersPictureTravelsWithIt(t *testing.T) {
	t.Parallel()

	const id = "dummyjson:154"
	uri := markDataURI(id, "Black Sun Glasses")

	encoded, found := strings.CutPrefix(uri, markDataURIPrefix)
	require.True(t, found, "Validate checks for exactly this prefix, so a picture without it is one no fetched offer may carry")

	svg, err := base64.StdEncoding.DecodeString(encoded)
	require.NoError(t, err, "a data URI a browser cannot decode is a broken image with extra steps")

	assert.Equal(t, string(markSVG(id, "Black Sun Glasses", liveMarkNote(id))), string(svg),
		"the URI has to carry this package's own drawing, or the picture on the screen is not the one this file argues about")
	assert.Contains(t, string(svg), "<title>Black Sun Glasses</title>",
		"the picture names the thing it is a picture of, which is what a screen reader is given in place of the mark")
	assert.Contains(t, string(svg), id,
		"a mark that did not say which offer it was drawn from could not be traced back to one")
}

// TestALiveMarkSaysWhereItCameFrom is the honesty half, and it is why the
// comment block is an argument to markSVG instead of a literal inside it.
//
// A picture drawn at start-up and carried inside an offer was not written by
// `make catalogue` and does not sit in a directory that program rewrites. Making
// the two byte-identical would have been simpler and would have put a false
// statement of provenance inside an artefact, in a repository whose subject is
// artefacts that say where they came from.
func TestALiveMarkSaysWhereItCameFrom(t *testing.T) {
	t.Parallel()

	const id = "dummyjson:154"
	live := string(markSVG(id, "Black Sun Glasses", liveMarkNote(id)))

	assert.NotContains(t, live, "make",
		"a mark drawn at start-up must not claim `make catalogue` wrote it, and must not point at a "+
			"directory that program rewrites — neither is true of it")
	assert.Contains(t, live, "carried inside the offer",
		"the comment is what tells whoever opens this picture why it is not a file like the others")
}

// TestTwoOffersGetTwoMarks is the check that keeps the derived shelf from
// reading as a mock-up of a shop.
//
// tools/catalogue rejected a small set of category illustrations on exactly that
// ground: a table repeating one drawing every third row does not read as a shop.
// What used to be worth saying here is that a copy of its drawing seeded on
// something coarser than the identifier would bring that back, and bring it back
// quietly — the parity test above compared sixty offers whose accents both
// implementations took from the category, so a category-seeded copy passed it.
//
// Issue #236 closed both halves. The accent is seeded on the identifier on both
// sides, so a copy reaching for the category now fails parity on most of the
// sixty — thirty-nine, as this snapshot falls — and markSVG has no category
// parameter to reach for, so it does not compile either.
//
// What is left is the claim the test always made, and the pair below no longer
// has to share a shelf to make it, because there is no shelf to share: the
// `"sunglasses"` both offers used to carry went with the parameter. Two
// identifiers draw two pictures; one identifier drawn twice draws one.
func TestTwoOffersGetTwoMarks(t *testing.T) {
	t.Parallel()

	first := markDataURI("dummyjson:154", "Black Sun Glasses")
	second := markDataURI("dummyjson:155", "Classic Sun Glasses")

	assert.NotEqual(t, first, second,
		"two offers drew the same mark, so a fetched shelf would be one picture repeated")
	assert.Equal(t, first, markDataURI("dummyjson:154", "Black Sun Glasses"),
		"a mark that varied between calls would give one offer two pictures across two searches in one run")
}
