package merchant

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/SkylinePlatform/agentic-payments/backend/internal/roles/merchant/shop"
)

// The two paths this file reaches, from this package's directory.
const (
	shippedCataloguePath = "../../../../deploy/catalogue.json"
	publicDir            = "../../../../frontend/public"
	derivedPrefix        = "/images/catalogue/derived/"
)

// derivedNote is tools/catalogue/mark.go's own comment block, character for
// character.
//
// It is the one part of the picture the two implementations legitimately
// disagree about — see liveMarkNote — so it is what this test hands markSVG to
// make the rest of the comparison exact. Writing it out here is not a second
// copy of anything load-bearing: if it drifts from what that program writes,
// the committed file it is compared against carries the other text and this
// test fails, which is precisely the drift it exists to catch.
func derivedNote(id string) string {
	return "    Generated by tools/catalogue from " + id + ". Do not hand-edit: `make\n" +
		"    catalogue` rewrites every file in this directory. The colours are the\n" +
		"    light-theme tokens frontend/src/styles.css declares, as literal hex.\n"
}

// TestALiveMarkIsTheMarkThisShopAlreadyDraws is what makes a duplicated drawing
// safe rather than merely small.
//
// tools/catalogue draws sixty pictures into frontend/public and commits them;
// this package draws one per fetched offer at start-up and carries it inside the
// offer. The two cannot share code — tools/catalogue is a separate Go module and
// a `package main`, so nothing here can import it and nothing there can import
// this — so the shelf reading as one shop rests on two implementations agreeing.
//
// This is the agreement, measured rather than asserted: every derived picture in
// the repository is re-drawn here and compared byte for byte. A change to either
// side fails in Go, on the branch that made it, instead of showing up as a table
// where half the rows came out of a different program.
//
// It is deliberately not a golden file of its own. The committed SVGs *are* the
// vectors, they are already regenerated by `make catalogue`, and a second copy
// beside this test would be a third thing to keep in step.
func TestALiveMarkIsTheMarkThisShopAlreadyDraws(t *testing.T) {
	t.Parallel()

	f, err := LoadCatalogue(shippedCataloguePath)
	require.NoError(t, err, "the shipped catalogue has to load, or there is nothing to compare against")

	compared := 0
	for _, offer := range f.Offers {
		if !strings.HasPrefix(offer.ImageURL, derivedPrefix) {
			continue
		}
		compared++

		committed, err := os.ReadFile(filepath.Join(publicDir, offer.ImageURL))
		require.NoError(t, err, "a derived picture the catalogue names is missing from the tree")

		assert.Equal(t, string(committed), string(markSVG(offer.ID, offer.Title, derivedNote(offer.ID))),
			"this package's drawing has drifted from tools/catalogue's, so the fetched half of the "+
				"shelf and the derived half would no longer read as one shop")
	}

	require.Greater(t, compared, 40,
		"nothing was compared, so this test proves nothing — the derived pictures have moved or "+
			"been renamed and the loop above quietly matched no offer")
}

// TestALiveOffersPictureTravelsWithIt is the property the image rule now rests
// on, stated directly rather than through Validate.
//
// A root-relative path is a promise that a file exists somewhere else, and issue
// #215 is the pull request about what happens when it does not. A data URI makes
// no such promise: it is the picture. So the assertions are that it decodes,
// that what comes out is the SVG this package draws, and that it names the offer
// it belongs to — which together mean a row cannot render a broken image without
// the offer itself being broken.
func TestALiveOffersPictureTravelsWithIt(t *testing.T) {
	t.Parallel()

	const id = "dummyjson:154"
	uri := markDataURI(id, "Black Sun Glasses")

	encoded, found := strings.CutPrefix(uri, markDataURIPrefix)
	require.True(t, found, "Validate checks for exactly this prefix, so a picture without it is one no fetched offer may carry")

	svg, err := base64.StdEncoding.DecodeString(encoded)
	require.NoError(t, err, "a data URI a browser cannot decode is a broken image with extra steps")

	assert.Equal(t, string(markSVG(id, "Black Sun Glasses", liveMarkNote(id))), string(svg),
		"the URI has to carry this package's own drawing, or the picture on the screen is not the one this file argues about")
	assert.Contains(t, string(svg), "<title>Black Sun Glasses</title>",
		"the picture names the thing it is a picture of, which is what a screen reader is given in place of the mark")
	assert.Contains(t, string(svg), id,
		"a mark that did not say which offer it was drawn from could not be traced back to one")
}

// TestALiveMarkSaysWhereItCameFrom is the honesty half, and it is why the
// comment block is an argument to markSVG instead of a literal inside it.
//
// A picture drawn at start-up and carried inside an offer was not written by
// `make catalogue` and does not sit in a directory that program rewrites. Making
// the two byte-identical would have been simpler and would have put a false
// statement of provenance inside an artefact, in a repository whose subject is
// artefacts that say where they came from.
func TestALiveMarkSaysWhereItCameFrom(t *testing.T) {
	t.Parallel()

	const id = "dummyjson:154"
	live := string(markSVG(id, "Black Sun Glasses", liveMarkNote(id)))

	assert.NotContains(t, live, "make",
		"a mark drawn at start-up must not claim `make catalogue` wrote it, and must not point at a "+
			"directory that program rewrites — neither is true of it")
	assert.Contains(t, live, "carried inside the offer",
		"the comment is what tells whoever opens this picture why it is not a file like the others")
}

// TestTwoOffersGetTwoMarks is the check that keeps the derived shelf from
// reading as a mock-up of a shop.
//
// tools/catalogue rejected a small set of category illustrations on exactly that
// ground: a table repeating one drawing every third row does not read as a shop.
// What used to be worth saying here is that a copy of its drawing seeded on
// something coarser than the identifier would bring that back, and bring it back
// quietly — the parity test above compared sixty offers whose accents both
// implementations took from the category, so a category-seeded copy passed it.
//
// Issue #236 closed both halves. The accent is seeded on the identifier on both
// sides, so a copy reaching for the category now fails parity on most of the
// sixty — thirty-nine, as this snapshot falls — and markSVG has no category
// parameter to reach for, so it does not compile either.
//
// What is left is the claim the test always made, and issue #279 is what made it
// falsifiable. Two calls to markDataURI with different identifiers **cannot**
// return the same string whatever the grid does: liveMarkNote embeds the
// identifier in the SVG comment and the title goes into a <title> element, so a
// markSVG that drew one identical grid for all 194 fetched offers passed this
// happily — which is precisely "a fetched shelf would be one picture repeated",
// the assertion's own message.
//
// So both offers below are drawn with one title and one note, and the identifier
// is the only thing left that differs. Anything that comes back different is the
// grid, which is the thing the claim is about.
func TestTwoOffersGetTwoMarks(t *testing.T) {
	t.Parallel()

	// Not liveMarkNote's text, because that is the half of the picture that
	// carries the identifier and would answer the question for the grid.
	const note = "    One note for both, so only the grid can differ.\n"
	first := string(markSVG("dummyjson:154", "Sun Glasses", note))
	second := string(markSVG("dummyjson:155", "Sun Glasses", note))

	assert.NotEqual(t, first, second,
		"two offers drew the same grid, so a fetched shelf would be one picture repeated with "+
			"nothing but its comment to tell the rows apart")

	// And the same offer twice. Held as a value from the line above rather than
	// spelled as two calls inside one assert.Equal, because this commit's
	// neighbour deleted a test for comparing an expression with itself and this
	// should not read like the thing that was deleted. What it catches is a
	// drawing that depends on how many marks came before it.
	//
	// **It is not the only thing that catches it, and the reason to keep it is
	// not exclusivity.** This said "reddens exactly this line and nothing else in
	// the suite"; issue #294 measured four other tests failing, and re-measuring
	// for that issue found five — a package-level counter mixed into markSVG's
	// hash reddens TestTwoOffersGetTwoMarks, TestALiveMarkIsTheMarkThisShopAlreadyDraws,
	// TestALiveOffersPictureTravelsWithIt, TestAFetchedOffersPictureIsDrawnFromItsOwnIdentifier
	// and three arms of TestEveryCharacterAFetchedPictureMayNotCarryIsRefusedOnItsOwn.
	//
	// The reason to keep it is what it says when it goes. The others fail saying a
	// picture is not the one committed, which sends a reader looking for a change
	// to the drawing; this one fails saying the drawing is not a function of its
	// arguments, which is the cause.
	drawnOnce := markDataURI("dummyjson:154", "Black Sun Glasses")
	assert.Equal(t, drawnOnce, markDataURI("dummyjson:154", "Black Sun Glasses"),
		"a mark that varied between calls would give one offer two pictures across two searches in one run")
}

// TestTheShopsPhotographIsShownAndAnythingElseBecomesAMark is the decision
// issue #300 made, at the one function that makes it.
//
// # Why the fallback needs a table rather than one case
//
// "Falls back when the shop gives no thumbnail" is the requirement, and taken
// literally it is one row: the empty string. The other rows are the ones that
// would each ship a broken image while satisfying a check written to the letter
// of that sentence — a relative path, which resolves against whichever page
// rendered it; `http://`, which a page served over https never draws at all;
// and `https://` with nothing after it, which is `src=""` arrived at through the
// branch that was supposed to prevent `src=""`.
//
// Every one of them ends in a mark rather than in a refusal, and that asymmetry
// is pictureFor's own doc: a malformed CDN path is nobody's claim about
// anything, and refusing it would make `make demo-live` hostage to one row in
// 194.
func TestTheShopsPhotographIsShownAndAnythingElseBecomesAMark(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name      string
		thumbnail string
		shown     bool
		why       string
	}{
		{
			name:      "the shop's own photograph",
			thumbnail: "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
			shown:     true,
			why: "this is the whole of issue #300, and a table where every row fell back would " +
				"pass without measuring the decision at all",
		},
		{
			name: "no thumbnail at all", thumbnail: "",
			why: "the requirement as written; `src=\"\"` resolves to the page itself and ships the " +
				"broken-image placeholder that issue #215 existed to end",
		},
		{
			name: "a thumbnail that is only whitespace", thumbnail: "   ",
			why: "a shop that sent spaces has sent no photograph, and this is the value that " +
				"arrives here if the decoder's own trim is ever removed",
		},
		{
			name: "a path relative to nothing", thumbnail: "product-images/1.webp",
			why: "it resolves against whichever page rendered it, which is the failure a " +
				"root-relative rule exists to prevent one kind of offer along",
		},
		{
			name: "a root-relative path", thumbnail: "/product-images/1.webp",
			why: "it resolves against this project's own server, where the shop's picture is not " +
				"and never will be",
		},
		{
			name: "a photograph over http", thumbnail: "http://cdn.dummyjson.com/1.webp",
			why: "a page served over https draws nothing at all for it — the browser blocks it as " +
				"mixed content — so it is strictly worse than the mark it now falls back to",
		},
		{
			name: "a scheme and no host", thumbnail: "https://",
			why: "this is what a prefix check alone accepts, and it is `src=\"\"` reached through " +
				"the branch that was supposed to prevent one",
		},
		{
			name: "a URL with a quote in it", thumbnail: "https://cdn.dummyjson.com/a\" onerror=\"x",
			why: "it is somebody else's string on its way into an img tag, and a rule this package " +
				"keeps is better than one borrowed from whatever renders the row",
		},
		{
			name: "a URL with a newline in it", thumbnail: "https://cdn.dummyjson.com/a\nb.webp",
			why: "the same, in the character that would break a header or a log line rather than " +
				"an attribute",
		},
		{
			name: "a photograph behind another scheme", thumbnail: "javascript:https://cdn.dummyjson.com/1.webp",
			why: "the rule is a prefix and not a substring, and this is the one value that tells " +
				"the two apart — an implementation asking whether the thumbnail *contains* " +
				"`https://` hands a browser whatever scheme came first",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			p := shop.Product{ID: "dummyjson:154", Title: "Black Sun Glasses", Thumbnail: tc.thumbnail}
			got := pictureFor(p)

			if tc.shown {
				assert.Equal(t, tc.thumbnail, got, tc.why)
				return
			}
			assert.Equal(t, markDataURI(p.ID, p.Title), got, tc.why)
		})
	}
}

// TestEveryCharacterAFetchedPictureMayNotCarryIsRefusedOnItsOwn is the class in
// liveImageForbidden, one character at a time and in both places that keep it.
//
// # Why the table above was not enough
//
// It has a row carrying a quote and a row carrying a newline, and the quote row
// reads `…/a" onerror="x` — a space *and* a quote. So the two characters stood
// in for each other: deleting `"` from liveImageForbidden left the row failing
// on the space, deleting the space left it failing on the quote, and both
// deletions individually left the whole suite green. That is an assertion that
// reddens only under some other mutation, which AGENTS.md names as one of the
// two shapes a green run cannot show you. `\t` and `\r` were in the class and
// in no row at all.
//
// # Why the class is written out as well as looped over
//
// The loop is derived from liveImageForbidden, which makes a character *added*
// to the class arrive with its own case rather than being covered by whatever
// else happens to be in the same string. It cannot do the opposite: a character
// *removed* takes its own case away with it, so the loop alone goes green on
// exactly the change that matters. Deleting the space, the tab, the quote or
// the carriage return from the constant was measured to leave the whole suite
// passing before the block below existed.
//
// So the class is stated once more here, one row per character with the reason
// it is in it, and its length is asserted — which is also the non-vacuity check
// AGENTS.md asks of a rule over a derived list, in a stronger form than "not
// empty". A character added without a row is a character nobody wrote a reason
// for; one removed is a rule quietly dropped.
//
// # Why both callers, in one test
//
// pictureFor and validateImage keep the same rule from opposite ends — one
// decides what to put in an offer, the other what a catalogue may hold — and
// the failure that matters is them disagreeing. Asking both of the same
// character is what makes a disagreement impossible to introduce quietly.
func TestEveryCharacterAFetchedPictureMayNotCarryIsRefusedOnItsOwn(t *testing.T) {
	t.Parallel()

	for _, c := range []struct {
		char rune
		why  string
	}{
		{' ', "a space is what separates one attribute from the next, so a URL carrying one is a picture and then something else the shop chose to put in the tag"},
		{'\t', "the same, in the whitespace a person reading the row would not see"},
		{'\r', "it ends a line in a header and in a log, and a URL that can end either is a URL that can start whatever comes after it"},
		{'\n', "the same, and it is the one an attacker reaches for first"},
		{'"', "it closes the attribute the picture is in, which is the whole of the difference between a src and a src plus an onerror"},
	} {
		assert.Contains(t, liveImageForbidden, string(c.char),
			"%q is not refused any more, and this row is the reason it was: %s", c.char, c.why)
	}
	assert.Len(t, liveImageForbidden, 5,
		"the class and the reasons written above it have to be the same set; a character in one and not the other is either a rule nobody stated a reason for or a reason for a rule that is gone")

	for _, c := range liveImageForbidden {
		t.Run(fmt.Sprintf("a photograph carrying %q and nothing else odd", c), func(t *testing.T) {
			t.Parallel()

			// One forbidden character and nothing else wrong: the prefix is
			// right, there is a host, and the rest is an ordinary CDN path. So
			// the only thing that can refuse it is this character.
			url := "https://cdn.dummyjson.com/a" + string(c) + "b.webp"

			p := shop.Product{ID: "dummyjson:154", Title: "Black Sun Glasses", Thumbnail: url}
			assert.Equal(t, markDataURI(p.ID, p.Title), pictureFor(p),
				"the merchant would put this in an img tag; every character in liveImageForbidden is there because one of them breaks the attribute, the header or the log line it lands in")

			entry := CatalogueEntry{ID: p.ID, Source: SourceLive, ImageURL: url}
			err := entry.validateImage()
			require.Error(t, err,
				"pictureFor and validateImage keep one rule from two ends, and a character only one of them refuses is a disagreement that shows up as `make demo-live` refusing to start, or as nothing at all")
			assert.ErrorIs(t, err, ErrInvalidCatalogue,
				"a catalogue this merchant will not sell from has to fail as an invalid catalogue, or the refusal reaches a caller as something else")
		})
	}
}

// TestAFetchedOffersPictureIsDrawnFromItsOwnIdentifier is the caller's half of
// what markSVG's missing category parameter cannot hold.
//
// Since issue #300 it reaches the drawing through pictureFor's fallback — the
// product below states no thumbnail — which is the path it was always about:
// what a mark is drawn *from* is only a question where a mark is drawn.
//
// Dropping that parameter stops the *drawing* reaching the shelf. It does not
// stop entryFor handing the shelf over, because a category is a string and so is
// an identifier — markDataURI(p.Category, p.Title) compiles, and it draws one
// picture per category for all 194 offers the recorded shop sells. That is the
// repeated shelf the test above refuses, arrived at down the one path that
// actually puts a picture on a fetched offer.
//
// Nothing else pins that path. The parity test and the two markDataURI tests all
// call the drawing themselves, and the tests that drive Extend see only what
// Validate asks of a fetched image_url — the data-URI prefix, which a picture
// drawn from the wrong string carries just as happily.
func TestAFetchedOffersPictureIsDrawnFromItsOwnIdentifier(t *testing.T) {
	t.Parallel()

	p := shop.Product{
		ID:       "dummyjson:154",
		Category: "sunglasses",
		Title:    "Black Sun Glasses",
	}

	assert.Equal(t, markDataURI(p.ID, p.Title), entryFor(p).ImageURL,
		"a fetched offer carries a picture drawn from something other than its own identifier, so "+
			"the shelf on the screen says what kind of thing a row is — which is the one claim a "+
			"mark is not allowed to make, and every offer on a shelf drawing the same picture is "+
			"the loudest way to make it")
}
